-- | Assemble a Hermes-ready bundle from the Canopy compiler's IIFE output.
--
-- The compiler already emits browser-free JS (feasibility report §1, Layer A): the
-- only host globals the runtime touches are @setTimeout@ (in @_Process_sleep@) and a
-- @scope@ object for @_Platform_export@. So "porting" the runtime is just a tiny
-- preamble that guarantees those exist on Hermes, plus a boot hook the native host
-- calls with the Fabric root tag. No compiler changes, no engine of our own.
module Canopy.Native.Bundle
  ( BundleInputs (..)
  , assembleBundle
  , hermesPreamble
  , bootTail
  , compiledMarker
  , compiledLineOffset
  , shiftSourceMap
  , stripSourceMapRef
  ) where

import           Data.Text (Text)
import qualified Data.Text as T

-- | Everything needed to wrap compiled JS into a runnable native bundle.
data BundleInputs = BundleInputs
  { biCompiledJs :: !Text  -- ^ the canopy compiler's IIFE output (sets globalThis.Elm)
  , biMainModule :: !Text  -- ^ the module exposing @main@, e.g. "Main"
  } deriving (Eq, Show)

-- | preamble ++ compiled JS ++ boot hook.
assembleBundle :: BundleInputs -> Text
assembleBundle inputs =
  T.intercalate "\n"
    [ hermesPreamble
    , compiledMarker
    , biCompiledJs inputs
    , bootTail (biMainModule inputs)
    ]

-- | The marker line that separates the host preamble from the compiled program. Named so
-- 'assembleBundle' and 'compiledLineOffset' stay in lockstep.
compiledMarker :: Text
compiledMarker = "// ---- compiled Canopy program (canopy make --output-format=iife) ----"

-- | The 0-based generated line at which the compiled program begins in the assembled
-- bundle — i.e. how many preamble lines every source-map mapping must shift past. Computed
-- from the exact pieces 'assembleBundle' joins before the compiled JS, so it stays correct
-- if the preamble grows; a golden test pins its concrete value.
compiledLineOffset :: Int
compiledLineOffset =
  T.count "\n" (hermesPreamble <> "\n" <> compiledMarker <> "\n")

-- | Re-align a V3 source map produced for the bare compiled IIFE so it matches the assembled
-- bundle, which prepends 'compiledLineOffset' preamble lines. The preamble carries no
-- mappings, so the shift is EXACT: prepend one empty generated line (a single @;@) per
-- preamble line to the VLQ @mappings@ string — no VLQ re-math. Also retitles the @file@
-- field. A no-op for a non-positive offset or a map with no @mappings@ field.
shiftSourceMap :: Int -> Text -> Text
shiftSourceMap n = retitle . shift
  where
    shift m
      | n <= 0    = m
      | otherwise = T.replace mappingsKey (mappingsKey <> T.replicate n ";") m
    retitle     = T.replace "\"file\":\"canopy.js\"" "\"file\":\"canopy.bundle.js\""
    mappingsKey = "\"mappings\":\""

-- | Drop any @\/\/# sourceMappingURL=@ trailer the compiler appended to the IIFE, so the
-- assembled bundle carries exactly one (correct) sourceMappingURL pointing at the aligned
-- @canopy.bundle.js.map@. The trailer is the last line, so removing it never shifts a
-- mapping's generated line.
stripSourceMapRef :: Text -> Text
stripSourceMapRef =
  T.unlines . filter (not . T.isPrefixOf "//# sourceMappingURL=" . T.stripStart) . T.lines

-- | Guarantees the handful of host globals the Canopy runtime expects exist on
-- Hermes. Inside React Native, @setTimeout@/@console@ already exist; in a bare Hermes
-- they may not, so we shim them off the microtask queue. Idempotent.
hermesPreamble :: Text
hermesPreamble =
  T.unlines
    [ "// GENERATED by canopy-native — Hermes host preamble."
    , "(function (g) {"
    , "  'use strict';"
    , "  if (typeof g.global === 'undefined') { g.global = g; }"
    , "  if (typeof g.self === 'undefined') { g.self = g; }"
    , "  // The Canopy scheduler's only host dependency: setTimeout (see _Process_sleep)."
    , "  if (typeof g.setTimeout === 'undefined') {"
    , "    var _q = []; var _pump = function () { var job = _q.shift(); if (job) job(); };"
    , "    g.setTimeout = function (fn, _ms) { _q.push(fn); Promise.resolve().then(_pump); return _q.length; };"
    , "    g.clearTimeout = function () {};"
    , "  }"
    , "  if (typeof g.console === 'undefined') {"
    , "    g.console = { log: function () {}, warn: function () {}, error: function () {} };"
    , "  }"
    , abiHelpers
    , "})(typeof globalThis !== 'undefined' ? globalThis : this);"
    ]

-- | The full F2..F9 / A2..A9 currying ABI as globals. The DEV-mode IIFE defines only
-- the arities its *live* code uses, yet bundled kernels (e.g. _List_map5) reference
-- higher arities — so the standalone bundle can crash with "F6 is not defined". We
-- provide the complete ABI here as a global fallback; the IIFE's own function-scoped
-- F2..Fn shadow these where present, and the missing high arities resolve to ours.
abiHelpers :: Text
abiHelpers =
  T.unlines
    [ "  if (typeof g.F2 === 'undefined') {"
    , "    g.F = function (arity, fun, wrapper) { wrapper.a = arity; wrapper.f = fun; return wrapper; };"
    , "    var mk = function (n) {"
    , "      return function (fun) {"
    , "        return g.F(n, fun, function () {"
    , "          var outer = arguments;"
    , "          var curry = function (got) {"
    , "            return got.length === n ? fun.apply(null, got)"
    , "              : function (x) { return curry(got.concat([x])); };"
    , "          };"
    , "          return curry(Array.prototype.slice.call(outer));"
    , "        });"
    , "      };"
    , "    };"
    , "    g.F2 = mk(2); g.F3 = mk(3); g.F4 = mk(4); g.F5 = mk(5);"
    , "    g.F6 = mk(6); g.F7 = mk(7); g.F8 = mk(8); g.F9 = mk(9);"
    , "    var ap = function (fun, args) { return fun.a === args.length ? fun.f.apply(null, args)"
    , "      : args.reduce(function (f, x) { return f(x); }, fun); };"
    , "    g.A2 = function (f,a,b) { return ap(f,[a,b]); };"
    , "    g.A3 = function (f,a,b,c) { return ap(f,[a,b,c]); };"
    , "    g.A4 = function (f,a,b,c,d) { return ap(f,[a,b,c,d]); };"
    , "    g.A5 = function (f,a,b,c,d,e) { return ap(f,[a,b,c,d,e]); };"
    , "    g.A6 = function (f,a,b,c,d,e,h) { return ap(f,[a,b,c,d,e,h]); };"
    , "    g.A7 = function (f,a,b,c,d,e,h,i) { return ap(f,[a,b,c,d,e,h,i]); };"
    , "    g.A8 = function (f,a,b,c,d,e,h,i,j) { return ap(f,[a,b,c,d,e,h,i,j]); };"
    , "    g.A9 = function (f,a,b,c,d,e,h,i,j,k) { return ap(f,[a,b,c,d,e,h,i,j,k]); };"
    , "  }"
    ]

-- | A boot hook the native host calls once it has a Fabric root tag and has installed
-- the @__fabric_*@ JSI functions: @globalThis.__canopy_boot(rootTag, flags)@ runs the
-- compiled program against that root. The program installs its own native event
-- dispatcher on boot (see external/native.js), so the host need only call this.
bootTail :: Text -> Text
bootTail mainModule =
  T.unlines
    [ "// GENERATED by canopy-native — native boot hook."
    , "(function (g) {"
    , "  g.__canopy_boot = function (rootTag, flags) {"
    , "    var elm = g.Elm || (g.scope && g.scope.Elm);"
    , "    if (!elm || !elm." <> mainModule <> ") {"
    , "      throw new Error('canopy: compiled module " <> mainModule <> " not found on global Elm');"
    , "    }"
    , "    return elm." <> mainModule <> ".init({ node: rootTag, flags: flags });"
    , "  };"
    , "})(typeof globalThis !== 'undefined' ? globalThis : this);"
    ]
