{-# LANGUAGE OverloadedStrings #-}

-- | gen-capability codegen (Phase 4, Capability M1) — THE spine of the capability fan-out.
--
-- A new native capability is normally 3-5 hand-written files in lockstep (the @.can@ effect
-- module, the Android module, the iOS module, the boot registration, the test mock) — which is
-- exactly why breadth stalled at ~12% of Expo. This emits the lot from ONE spec, so adding a
-- capability is a command, not a multi-day chore:
--
--     canopy-native gen-capability Vibration --methods vibrate,cancel
--
-- It generates COMPILABLE skeletons (one-shot methods that resolve @null@) the author then fills:
--   * @Native.<Name>.can@      — Task wrappers over the C1 @Native.Module.call@ ABI.
--   * @<Name>Module.java@       — a JniModule(\"<Name>\") dispatcher (the PlatformModule shape).
--   * a boot registration line  — to paste into CanopyHostJni.cpp (M3 makes this a generated include).
--   * a harness mock entry       — so the device-free tests can stand the capability in.
--
-- Streaming (Sub) capabilities are out of scope here (they need the StreamingJniModule manager);
-- one-shots are the common case and the proof of the authoring system.
module Canopy.Native.CapabilityCodegen
  ( CapabilitySpec (..)
  , renderCanModule
  , renderJavaModule
  , renderBootLine
  , renderMockEntry
  ) where

import           Data.Text (Text)
import qualified Data.Text as T

-- | A capability: its PascalCase name + its one-shot method names.
data CapabilitySpec = CapabilitySpec
  { capName    :: !Text
  , capMethods :: ![Text]
  } deriving (Eq, Show)

nl :: [Text] -> Text
nl = T.intercalate "\n"

-- | The @.can@ effect module: a `Task` wrapper per method over `Native.Module.call`. Each starts
-- as a no-arg, unit-result one-shot the author refines (args via Encode, result via a decoder).
renderCanModule :: CapabilitySpec -> Text
renderCanModule spec = nl $
  [ "module Native." <> capName spec <> " exposing"
  , "    ( " <> T.intercalate ", " (capMethods spec) <> " )"
  , ""
  , "{-| " <> capName spec <> " capability (generated by `canopy-native gen-capability`)."
  , ""
  , "Each method is a one-shot `Task` you run with `Task.attempt`. The generated body is a no-arg"
  , "call that resolves `()`; fill in the args (via `Encode`) + the result decoder to match the"
  , "Java/Swift implementation."
  , ""
  , "@docs " <> T.intercalate ", " (capMethods spec)
  , ""
  , "-}"
  , ""
  , "import Json.Decode as Decode"
  , "import Json.Encode as Encode"
  , "import Native.Module as NM"
  , "import Task exposing (Task)"
  ]
  ++ concatMap (canMethod (capName spec)) (capMethods spec)

canMethod :: Text -> Text -> [Text]
canMethod name method =
  [ ""
  , ""
  , "{-| TODO: document " <> method <> ". -}"
  , method <> " : Task NM.Error ()"
  , method <> " ="
  , "    NM.call \"" <> name <> "\" \"" <> method <> "\" (Encode.object []) (Decode.succeed ())"
  ]

-- | The Android @<Name>Module.java@: a JniModule dispatcher (the PlatformModule shape). Each
-- method is a stub that resolves @null@; the author fills the body + chooses threading.
renderJavaModule :: CapabilitySpec -> Text
renderJavaModule spec = nl $
  [ "// " <> capName spec <> "Module.java — generated by `canopy-native gen-capability`."
  , "//"
  , "// A JniModule(\"" <> capName spec <> "\") capability: __canopy_call(\"" <> capName spec <> "\", method, …)"
  , "// routes to invoke() here. Registered at boot (see the printed registration line). Each method"
  , "// stub resolves null — fill in the body using `args`, and hop to a worker/main thread as the"
  , "// API requires (HttpModule runs off-thread; PlatformModule posts to the main looper)."
  , "package com.canopyhost.modules;"
  , ""
  , "import com.canopyhost.CanopyHostJni;"
  , ""
  , "import org.json.JSONObject;"
  , ""
  , "public final class " <> capName spec <> "Module {"
  , ""
  , "  public static void invoke(String method, String argsJson, String callId) {"
  , "    try {"
  , "      JSONObject args = new JSONObject(argsJson == null || argsJson.isEmpty() ? \"{}\" : argsJson);"
  , "      switch (method) {"
  ]
  ++ concatMap javaCase (capMethods spec) ++
  [ "        default:"
  , "          reject(callId, \"module_not_found\", \"" <> capName spec <> ".\" + method);"
  , "      }"
  , "    } catch (Throwable t) {"
  , "      reject(callId, \"rejected\", t.getClass().getSimpleName()"
  , "          + (t.getMessage() != null ? \": \" + t.getMessage() : \"\"));"
  , "    }"
  , "  }"
  , ""
  , "  private static void resolve(String callId, String resultJson) {"
  , "    CanopyHostJni.resolveModule(callId, \"\", resultJson);"
  , "  }"
  , ""
  , "  private static void reject(String callId, String code, String message) {"
  , "    try {"
  , "      JSONObject err = new JSONObject();"
  , "      err.put(\"code\", code);"
  , "      err.put(\"message\", message == null ? \"\" : message);"
  , "      CanopyHostJni.resolveModule(callId, err.toString(), \"\");"
  , "    } catch (Exception e) {"
  , "      CanopyHostJni.resolveModule(callId, \"{\\\"code\\\":\\\"rejected\\\"}\", \"\");"
  , "    }"
  , "  }"
  , ""
  , "  private " <> capName spec <> "Module() {}"
  , "}"
  ]

javaCase :: Text -> [Text]
javaCase method =
  [ "        case \"" <> method <> "\": {"
  , "          // TODO: implement " <> method <> " using `args`."
  , "          resolve(callId, \"null\");"
  , "          break;"
  , "        }"
  ]

-- | The C++ boot registration line to paste into CanopyHostJni.cpp's registry block.
renderBootLine :: CapabilitySpec -> Text
renderBootLine spec =
  "  g_registry->registerModule(std::make_shared<canopy::JniModule>(\"" <> capName spec <> "\"));"

-- | A harness mock entry (for harness/mock-native-modules.js) — each method completes null.
renderMockEntry :: CapabilitySpec -> Text
renderMockEntry spec = nl $
  [ "registerModule('" <> capName spec <> "', {" ]
  ++ map (\m -> "  " <> m <> ": (args, ctx) => ctx.complete(null, 'null'),") (capMethods spec)
  ++ [ "});" ]
