{-# LANGUAGE OverloadedStrings #-}

-- | gen-capability codegen (Phase 4, Capability M1; evolved by AUTO-E-DELETE / plan §5 Phase E) —
-- THE spine of the capability fan-out.
--
-- A new native capability is normally 3-5 hand-written files in lockstep (the @.can@ module, the
-- Android module, the iOS module, the boot registration, the test mock) — which is exactly why
-- breadth stalled at ~12% of Expo. This emits the lot from ONE spec, so adding a capability is a
-- command, not a multi-day chore:
--
--     canopy-native gen-capability Vibration --methods vibrate,cancel
--
-- AUTO-E-DELETE evolution: it no longer emits loose files + PRINTS a boot line for a human to paste
-- into CanopyHostJni.cpp (that anti-pattern is gone — the host boot block was deleted). It now emits
-- a FULL SELF-CONTAINED PACKAGE, the native analogue of a web capability package that ships its own
-- @external/*.js@ (DoD #6: "gen-capability foo produces a package that satisfies (1)"):
--
--     canopy/<name>/
--       canopy.json                         -- package metadata + deps (canopy/native for Native.Module)
--       native.json                         -- the autolink manifest (`canopy-native` reads this, the
--                                              compiler never does); declaring the module here + the
--                                              native/ sources is all it takes to autolink with NO host edit
--       src/<Name>.can                      -- Task wrappers over the C1 Native.Module.call ABI
--       native/android/<Name>Module.java    -- a JniModule("<Name>") dispatcher (the PlatformModule shape)
--       native/ios/Canopy<Name>Module.mm    -- the <CanopyModule> twin (the iOS by-name bridge resolves it)
--       harness/mock.js                     -- a device-free harness mock (each method completes null)
--
-- It generates COMPILABLE skeletons (one-shot methods that resolve @null@) the author then fills.
-- Streaming (Sub) capabilities are out of scope here (they need the StreamingJniModule manager);
-- one-shots are the common case and the proof of the authoring system.
--
-- The legacy file-level renderers ('renderCanModule' / 'renderJavaModule' / 'renderBootLine' /
-- 'renderMockEntry') are retained (and re-used by 'packageFiles') so existing callers + tests keep
-- working; 'renderBootLine' now documents that the boot line is GENERATED by the autolinker, not
-- pasted by hand.
module Canopy.Native.CapabilityCodegen
  ( CapabilitySpec (..)
  , renderCanModule
  , renderJavaModule
  , renderIosModule
  , renderCanopyJson
  , renderPackageNativeJson
  , renderBootLine
  , renderMockEntry
    -- * Full self-contained package generation (AUTO-E-DELETE / plan §5 Phase E)
  , GeneratedFile (..)
  , packageFiles
  ) where

import           Data.Text (Text)
import qualified Data.Text as T

-- | A capability: its PascalCase name + its one-shot method names.
data CapabilitySpec = CapabilitySpec
  { capName    :: !Text
  , capMethods :: ![Text]
  } deriving (Eq, Show)

nl :: [Text] -> Text
nl = T.intercalate "\n"

-- | The @.can@ module: a `Task` wrapper per method over `Native.Module.call`. Each starts as a
-- no-arg, unit-result one-shot the author refines (args via Encode, result via a decoder).
renderCanModule :: CapabilitySpec -> Text
renderCanModule spec = nl $
  [ "module " <> capName spec <> " exposing"
  , "    ( " <> T.intercalate ", " (capMethods spec) <> " )"
  , ""
  , "{-| " <> capName spec <> " capability (generated by `canopy-native gen-capability`)."
  , ""
  , "Each method is a one-shot `Task` you run with `Task.attempt`. The generated body is a no-arg"
  , "call that resolves `()`; fill in the args (via `Encode`) + the result decoder to match the"
  , "Java/Swift implementation. Every op routes through the C1 `Native.Module.call` ABI — the host"
  , "module `com.canopyhost.modules." <> capName spec <> "Module` (Android) /"
  , "`Canopy" <> capName spec <> "Module` (iOS) is autolinked from this package's native.json with"
  , "NO edit to canopy/native or the host shell."
  , ""
  , "@docs " <> T.intercalate ", " (capMethods spec)
  , ""
  , "-}"
  , ""
  , "import Json.Decode as Decode"
  , "import Json.Encode as Encode"
  , "import Native.Module as NM"
  , "import Task exposing (Task)"
  ]
  ++ concatMap (canMethod (capName spec)) (capMethods spec)

canMethod :: Text -> Text -> [Text]
canMethod name method =
  [ ""
  , ""
  , "{-| TODO: document " <> method <> ". -}"
  , method <> " : Task NM.Error ()"
  , method <> " ="
  , "    NM.call \"" <> name <> "\" \"" <> method <> "\" (Encode.object []) (Decode.succeed ())"
  ]

-- | The Android @<Name>Module.java@: a JniModule dispatcher (the PlatformModule shape). Each
-- method is a stub that resolves @null@; the author fills the body + chooses threading.
renderJavaModule :: CapabilitySpec -> Text
renderJavaModule spec = nl $
  [ "// " <> capName spec <> "Module.java — generated by `canopy-native gen-capability`."
  , "//"
  , "// A JniModule(\"" <> capName spec <> "\") capability: __canopy_call(\"" <> capName spec <> "\", method, …)"
  , "// routes to invoke() here. AUTOLINKED from this package's native.json (the autolinker emits the"
  , "// registration into the host's generated registrant — NO host boot edit). Each method stub"
  , "// resolves null — fill in the body using `args`, and hop to a worker/main thread as the API"
  , "// requires (HttpModule runs off-thread; PlatformModule posts to the main looper)."
  , "package com.canopyhost.modules;"
  , ""
  , "import com.canopyhost.CanopyHostJni;"
  , ""
  , "import org.json.JSONObject;"
  , ""
  , "public final class " <> capName spec <> "Module {"
  , ""
  , "  public static void invoke(String method, String argsJson, String callId) {"
  , "    try {"
  , "      JSONObject args = new JSONObject(argsJson == null || argsJson.isEmpty() ? \"{}\" : argsJson);"
  , "      switch (method) {"
  ]
  ++ concatMap javaCase (capMethods spec) ++
  [ "        default:"
  , "          reject(callId, \"module_not_found\", \"" <> capName spec <> ".\" + method);"
  , "      }"
  , "    } catch (Throwable t) {"
  , "      reject(callId, \"rejected\", t.getClass().getSimpleName()"
  , "          + (t.getMessage() != null ? \": \" + t.getMessage() : \"\"));"
  , "    }"
  , "  }"
  , ""
  , "  private static void resolve(String callId, String resultJson) {"
  , "    CanopyHostJni.resolveModule(callId, \"\", resultJson);"
  , "  }"
  , ""
  , "  private static void reject(String callId, String code, String message) {"
  , "    try {"
  , "      JSONObject err = new JSONObject();"
  , "      err.put(\"code\", code);"
  , "      err.put(\"message\", message == null ? \"\" : message);"
  , "      CanopyHostJni.resolveModule(callId, err.toString(), \"\");"
  , "    } catch (Exception e) {"
  , "      CanopyHostJni.resolveModule(callId, \"{\\\"code\\\":\\\"rejected\\\"}\", \"\");"
  , "    }"
  , "  }"
  , ""
  , "  private " <> capName spec <> "Module() {}"
  , "}"
  ]

javaCase :: Text -> [Text]
javaCase method =
  [ "        case \"" <> method <> "\": {"
  , "          // TODO: implement " <> method <> " using `args`."
  , "          resolve(callId, \"null\");"
  , "          break;"
  , "        }"
  ]

-- | The iOS @Canopy<Name>Module.mm@: a @<CanopyModule>@ twin (the §4.1 protocol the §4.2 by-name
-- bridge resolves at boot). Each method is a stub that resolves the literal JSON @null@; the author
-- fills the body + chooses the dispatch queue (a UIKit API hops to the main queue like Brightness).
-- This is the iOS analogue of 'renderJavaModule', so a gen-capability package is package-resident on
-- BOTH platforms out of the box (the AUTO-E-DELETE parity guarantee).
renderIosModule :: CapabilitySpec -> Text
renderIosModule spec = nl $
  [ "// Canopy" <> capName spec <> "Module.mm — generated by `canopy-native gen-capability`."
  , "//"
  , "// The iOS twin of native/android/" <> capName spec <> "Module.java. Adopts the §4.1 <CanopyModule>"
  , "// protocol; the §4.2 CanopyNativeModuleBridge wraps it into a canopy::NativeModule and registers"
  , "// it by name, so __canopy_call(module=\"" <> capName spec <> "\", method, …) routes to -invokeMethod:"
  , "// here. AUTOLINKED from this package's native.json (the generated CanopyGeneratedCaps() names it)"
  , "// — NO host boot edit. Each method stub resolves the literal JSON null; fill in the body."
  , "#import <Foundation/Foundation.h>"
  , "#import <UIKit/UIKit.h>"
  , ""
  , "#import \"CanopyModule.h\"          // the <CanopyModule> protocol + CanopyComplete"
  , "#import \"CanopyModuleSupport.h\"   // CanopyParseArgs / CanopyResolve / CanopyReject helpers"
  , ""
  , "@interface Canopy" <> capName spec <> "Module : NSObject <CanopyModule>"
  , "@end"
  , ""
  , "@implementation Canopy" <> capName spec <> "Module"
  , ""
  , "- (NSString *)moduleName { return @\"" <> capName spec <> "\"; }"
  , ""
  , "- (BOOL)invokeMethod:(NSString *)method"
  , "                args:(NSString *)argsJson"
  , "              callId:(NSString *)callId"
  , "            complete:(CanopyComplete)complete {"
  , "  NSDictionary *args = CanopyParseArgs(argsJson);  (void)args;  // TODO: read args per method"
  ]
  ++ concatMap iosCase (capMethods spec) ++
  [ "  return NO;  // unknown method → ModuleNotFound"
  , "}"
  , ""
  , "@end"
  ]

iosCase :: Text -> [Text]
iosCase method =
  [ "  if ([method isEqualToString:@\"" <> method <> "\"]) {"
  , "    // TODO: implement " <> method <> " using `args`; hop to the right queue if it touches UIKit."
  , "    CanopyResolveNull(complete);  // resolves the literal JSON null"
  , "    return YES;"
  , "  }"
  ]

-- | The package @canopy.json@: a @type \"package\"@ named @canopy/\<name\>@ depending on
-- @canopy/native@ (for @Native.Module@), mirroring @canopy/image@'s canopy.json. @\<name\>@ is the
-- lowercased capability name (the package dir convention).
renderCanopyJson :: CapabilitySpec -> Text
renderCanopyJson spec = nl $
  [ "{"
  , "    \"type\": \"package\","
  , "    \"name\": \"canopy/" <> pkgName <> "\","
  , "    \"summary\": \"" <> capName spec <> " — a native capability generated by `canopy-native gen-capability`. Fill in the summary.\","
  , "    \"license\": \"BSD-3-Clause\","
  , "    \"version\": \"1.0.0\","
  , "    \"exposed-modules\": ["
  , "        \"" <> capName spec <> "\""
  , "    ],"
  , "    \"canopy-version\": \"0.19.0 <= v < 0.20.0\","
  , "    \"dependencies\": {"
  , "        \"canopy/core\": \"1.0.0 <= v < 2.0.0\","
  , "        \"canopy/json\": \"1.0.0 <= v < 2.0.0\","
  , "        \"canopy/native\": \"0.1.0 <= v < 1.0.0\""
  , "    },"
  , "    \"test-dependencies\": {}"
  , "}"
  ]
  where pkgName = T.toLower (capName spec)

-- | The package @native.json@ autolink manifest — the schema 'Canopy.Native.Autolink.NativeManifest'
-- parses. It declares the ONE module (a plain @jni@ one-shot) + points at the @native/android@ and
-- @native/ios@ sources. Shipping this + the native/ dirs is all it takes for @canopy-native build@ to
-- autolink the capability from the dependency graph with ZERO host edits — the native analogue of a
-- web package shipping @external/*.js@. (Built as text, matching 'Canopy.Native.Extract's hand-emitter
-- style, so the tool keeps a minimal dependency set.)
renderPackageNativeJson :: CapabilitySpec -> Text
renderPackageNativeJson spec = nl $
  [ "{"
  , "  \"_comment\": \"native.json — the canopy-native autolink manifest for canopy/" <> T.toLower (capName spec)
      <> ". GENERATED by `canopy-native gen-capability`. The COMPILER never reads this; only `canopy-native` does. "
      <> "Declaring the module here + shipping native/android + native/ios is all it takes to autolink this "
      <> "capability into an app with NO host edits.\","
  , "  \"modules\": ["
  , "    { \"name\": \"" <> capName spec <> "\", \"kind\": \"jni\" }"
  , "  ],"
  , "  \"androidSource\": \"native/android\","
  , "  \"iosSource\": \"native/ios\""
  , "}"
  ]

-- | The C++ boot registration line. Historically PRINTED for a human to paste into
-- CanopyHostJni.cpp's registry block; after AUTO-E-DELETE that block is GONE — the registration is
-- GENERATED by the autolinker from the package's native.json. Kept (and exported) for the existing
-- tests + as documentation of the exact line the generated registrant emits for this capability.
renderBootLine :: CapabilitySpec -> Text
renderBootLine spec =
  "  reg.registerModule(std::make_shared<canopy::JniModule>(\"" <> capName spec <> "\"));"

-- | A harness mock entry (for a device-free test harness) — each method completes null.
renderMockEntry :: CapabilitySpec -> Text
renderMockEntry spec = nl $
  [ "registerModule('" <> capName spec <> "', {" ]
  ++ map (\m -> "  " <> m <> ": (args, ctx) => ctx.complete(null, 'null'),") (capMethods spec)
  ++ [ "});" ]

-- ---------------------------------------------------------------------------------------------
-- Full self-contained package generation (AUTO-E-DELETE / plan §5 Phase E)
-- ---------------------------------------------------------------------------------------------

-- | One file the generator emits: a package-root-relative path + its contents. The CLI writes each
-- under @\<outDir\>/canopy/\<name\>/@ (or wherever the caller roots the package).
data GeneratedFile = GeneratedFile
  { gfPath    :: !FilePath  -- ^ package-relative path, e.g. "src/Vibration.can"
  , gfContent :: !Text
  } deriving (Eq, Show)

-- | The complete set of files for a self-contained capability package. This is the AUTO-E-DELETE
-- deliverable: @gen-capability Foo@ produces a package satisfying DoD #1 (canopy.json + src/Foo.can +
-- native/android + native/ios) with no manual file placement, so adding the capability to an app is
-- "add a dependency" — exactly like @canopy/http@ ships @external/http.js@.
--
-- The package-relative layout (rooted at @canopy/\<name\>/@):
--
--   * @canopy.json@                          — package metadata + deps
--   * @native.json@                          — the autolink manifest
--   * @src/\<Name\>.can@                      — the Canopy module (Task wrappers)
--   * @native/android/\<Name\>Module.java@    — the Android JniModule dispatcher
--   * @native/ios/Canopy\<Name\>Module.mm@    — the iOS <CanopyModule> twin
--   * @harness/mock.js@                       — a device-free harness mock
packageFiles :: CapabilitySpec -> [GeneratedFile]
packageFiles spec =
  [ GeneratedFile "canopy.json"                                        (renderCanopyJson spec       <> "\n")
  , GeneratedFile "native.json"                                        (renderPackageNativeJson spec <> "\n")
  , GeneratedFile ("src/" <> name <> ".can")                           (renderCanModule spec        <> "\n")
  , GeneratedFile ("native/android/" <> name <> "Module.java")         (renderJavaModule spec       <> "\n")
  , GeneratedFile ("native/ios/Canopy" <> name <> "Module.mm")         (renderIosModule spec        <> "\n")
  , GeneratedFile "harness/mock.js"                                    (renderMockEntry spec        <> "\n")
  ]
  where name = T.unpack (capName spec)
