-- | Generate the Canopy-fact → Fabric-prop mapping glue from the typed component
-- model, for three targets that all stay in lock-step because they come from one
-- source ('Canopy.Native.Component.defaultComponents'):
--
--   * a JSON manifest the Hermes host bootstrap loads to coerce props + validate tags
--   * a C++ header exposing the same manifest to the JSI mount layer
--   * a TypeScript declaration of the component surface (editor help / docs)
--
-- These functions are PURE (spec in, source string out) so they unit-test cleanly —
-- the same discipline the Canopy compiler's own codegen follows.
module Canopy.Native.Codegen
  ( manifestValue
  , renderManifestJSON
  , renderCppHeader
  , renderTypeScript
  ) where

import           Canopy.Native.Component
import           Data.Aeson (Value (..), object, (.=))
import qualified Data.Aeson as Aeson
import qualified Data.Aeson.Key as Key
import qualified Data.ByteString.Lazy as BL
import qualified Data.Map.Strict as Map
import           Data.Text (Text)
import qualified Data.Text as T

-- ---------------------------------------------------------------------------
-- JSON manifest
-- ---------------------------------------------------------------------------

-- | The manifest as an Aeson value: every component with its Fabric name, platform
-- classes, and a prop→kind table.
manifestValue :: [ComponentSpec] -> Value
manifestValue comps =
  object
    [ "version"    .= (1 :: Int)
    , "generator"  .= ("canopy-native codegen" :: Text)
    , "components" .= object (map componentEntry comps)
    ]

componentEntry :: ComponentSpec -> (Aeson.Key, Value)
componentEntry c =
  Key.fromText (compCanopyTag c) .= object
    [ "fabricName" .= compFabricName c
    , "ios"        .= compIOSClass c
    , "android"    .= compAndroidClass c
    , "props"      .= object (map propEntry (compProps c))
    ]

propEntry :: PropSpec -> (Aeson.Key, Value)
propEntry p = Key.fromText (propName p) .= kindText (propKind p)

kindText :: PropKind -> Text
kindText = \case
  PropString -> "string"
  PropFloat  -> "float"
  PropColor  -> "color"
  PropBool   -> "bool"
  PropEvent  -> "event"

-- | Render the manifest as pretty-ish JSON bytes (compact arrays, one key per line is
-- not worth a dependency — Aeson's encoder is deterministic and diff-stable).
renderManifestJSON :: [ComponentSpec] -> BL.ByteString
renderManifestJSON = Aeson.encode . manifestValue

-- ---------------------------------------------------------------------------
-- C++ header (consumed by the JSI mount layer in host/shared/cpp)
-- ---------------------------------------------------------------------------

-- | A self-contained header exposing the valid tags and the (tag,prop) float set the
-- JSI layer coerces. Generated, never hand-edited.
renderCppHeader :: [ComponentSpec] -> Text
renderCppHeader comps =
  T.unlines $
    [ "// GENERATED by canopy-native codegen — do not edit."
    , "#pragma once"
    , "#include <string>"
    , "#include <unordered_set>"
    , ""
    , "namespace canopy {"
    , ""
    , "// Tags external/native.js may create via __fabric_createView."
    , "inline const std::unordered_set<std::string>& canopyValidTags() {"
    , "  static const std::unordered_set<std::string> tags = {"
    ]
    ++ map (indent2 . cppStr . compCanopyTag) comps
    ++
    [ "  };"
    , "  return tags;"
    , "}"
    , ""
    , "// (tag|prop) pairs whose Canopy string value must be coerced to a float for Yoga."
    , "inline const std::unordered_set<std::string>& canopyFloatProps() {"
    , "  static const std::unordered_set<std::string> floats = {"
    ]
    ++ map (indent2 . cppStr . pairKey) (floatStyleKeys comps)
    ++
    [ "  };"
    , "  return floats;"
    , "}"
    , ""
    , "} // namespace canopy"
    ]
  where
    pairKey (tag, prop) = tag <> "|" <> prop

cppStr :: Text -> Text
cppStr s = "\"" <> s <> "\","

indent2 :: Text -> Text
indent2 = ("    " <>)

-- ---------------------------------------------------------------------------
-- TypeScript surface (editor help; the host JS can import the manifest too)
-- ---------------------------------------------------------------------------

-- | A TypeScript description of the component surface, grouping prop kinds. Useful as
-- documentation and as a typed view of the manifest for any JS host tooling.
renderTypeScript :: [ComponentSpec] -> Text
renderTypeScript comps =
  T.unlines $
    [ "// GENERATED by canopy-native codegen — do not edit."
    , "export type CanopyPropKind = 'string' | 'float' | 'color' | 'bool' | 'event';"
    , ""
    , "export interface CanopyComponent {"
    , "  fabricName: string;"
    , "  ios: string;"
    , "  android: string;"
    , "  props: Record<string, CanopyPropKind>;"
    , "}"
    , ""
    , "export const canopyComponents: Record<string, CanopyComponent> = {"
    ]
    ++ map tsComponent comps
    ++ [ "};" ]

tsComponent :: ComponentSpec -> Text
tsComponent c =
  T.concat
    [ "  ", quote (compCanopyTag c), ": { fabricName: ", quote (compFabricName c)
    , ", ios: ", quote (compIOSClass c), ", android: ", quote (compAndroidClass c)
    , ", props: { ", T.intercalate ", " (map tsProp (dedupProps (compProps c))), " } },"
    ]

tsProp :: PropSpec -> Text
tsProp p = quote (propName p) <> ": " <> quote (kindText (propKind p))

-- Components share layout/view props; keep the last kind seen per name, deterministic.
dedupProps :: [PropSpec] -> [PropSpec]
dedupProps ps =
  [ PropSpec n k | (n, k) <- Map.toList (Map.fromList [ (propName p, propKind p) | p <- ps ]) ]

quote :: Text -> Text
quote s = "'" <> s <> "'"
