// BatteryModule.java — generated by `canopy-native gen-capability`, then filled in.
//
// A JniModule("Battery") capability: __canopy_call("Battery", method, …)
// routes to invoke() here. Registered at boot (see the printed registration line).
//
// Wire contract (must match Native/Battery.can):
//   status {} -> {"level":<float>,"charging":<bool>}
//
// A sticky ACTION_BATTERY_CHANGED broadcast is read synchronously (registerReceiver(null, …)
// returns the last sticky Intent immediately), so no thread hop is needed.
package com.canopyhost.modules;

import android.content.Context;
import android.content.Intent;
import android.content.IntentFilter;
import android.os.BatteryManager;

import com.canopyhost.CanopyHostJni;
import com.canopyhost.MainActivity;

import org.json.JSONObject;

public final class BatteryModule {

  public static void invoke(String method, String argsJson, String callId) {
    try {
      JSONObject args = new JSONObject(argsJson == null || argsJson.isEmpty() ? "{}" : argsJson);
      switch (method) {
        case "status": {
          Context ctx = MainActivity.appContext();
          if (ctx == null) { reject(callId, "rejected", "no application context"); break; }

          Intent i = ctx.registerReceiver(null, new IntentFilter(Intent.ACTION_BATTERY_CHANGED));
          if (i == null) { reject(callId, "rejected", "no battery status available"); break; }

          int level = i.getIntExtra(BatteryManager.EXTRA_LEVEL, -1);
          int scale = i.getIntExtra(BatteryManager.EXTRA_SCALE, -1);
          int status = i.getIntExtra(BatteryManager.EXTRA_STATUS, -1);

          double pct = (level >= 0 && scale > 0) ? ((double) level / (double) scale) : 0.0;
          boolean charging = status == BatteryManager.BATTERY_STATUS_CHARGING
              || status == BatteryManager.BATTERY_STATUS_FULL;

          JSONObject out = new JSONObject();
          out.put("level", pct);
          out.put("charging", charging);
          resolve(callId, out.toString());
          break;
        }
        default:
          reject(callId, "module_not_found", "Battery." + method);
      }
    } catch (Throwable t) {
      reject(callId, "rejected", t.getClass().getSimpleName()
          + (t.getMessage() != null ? ": " + t.getMessage() : ""));
    }
  }

  private static void resolve(String callId, String resultJson) {
    CanopyHostJni.resolveModule(callId, "", resultJson);
  }

  private static void reject(String callId, String code, String message) {
    try {
      JSONObject err = new JSONObject();
      err.put("code", code);
      err.put("message", message == null ? "" : message);
      CanopyHostJni.resolveModule(callId, err.toString(), "");
    } catch (Exception e) {
      CanopyHostJni.resolveModule(callId, "{\"code\":\"rejected\"}", "");
    }
  }

  private BatteryModule() {}
}
