// BrightnessModule.java — generated by `canopy-native gen-capability`, then filled in.
//
// A JniModule("Brightness") capability: __canopy_call("Brightness", method, …)
// routes to invoke() here. Registered at boot (see the printed registration line).
//
// Wire contract (must match Native/Brightness.can):
//   get  {}  -> {level:<float 0.0..1.0>}
//
// Reading the system screen brightness needs NO permission. SCREEN_BRIGHTNESS is a 0..255 int;
// we normalize to 0.0..1.0. The read is fast, so we resolve synchronously inside invoke (no
// thread hop). (Setting brightness would need WRITE_SETTINGS — out of scope; get only.)
package com.canopyhost.modules;

import com.canopyhost.CanopyHostJni;
import com.canopyhost.MainActivity;

import org.json.JSONObject;

public final class BrightnessModule {

  public static void invoke(String method, String argsJson, String callId) {
    try {
      JSONObject args = new JSONObject(argsJson == null || argsJson.isEmpty() ? "{}" : argsJson);
      switch (method) {
        case "get": {
          android.content.Context ctx = MainActivity.appContext();
          if (ctx == null) {
            reject(callId, "rejected", "no application context");
            break;
          }
          int b = android.provider.Settings.System.getInt(
              ctx.getContentResolver(),
              android.provider.Settings.System.SCREEN_BRIGHTNESS,
              0);
          double level = b / 255.0;
          if (level < 0.0) level = 0.0;
          if (level > 1.0) level = 1.0;
          JSONObject out = new JSONObject();
          out.put("level", level);
          android.util.Log.i("Canopy", "Brightness.get -> " + level + " — generated capability ran");
          resolve(callId, out.toString());
          break;
        }
        default:
          reject(callId, "module_not_found", "Brightness." + method);
      }
    } catch (Throwable t) {
      reject(callId, "rejected", t.getClass().getSimpleName()
          + (t.getMessage() != null ? ": " + t.getMessage() : ""));
    }
  }

  private static void resolve(String callId, String resultJson) {
    CanopyHostJni.resolveModule(callId, "", resultJson);
  }

  private static void reject(String callId, String code, String message) {
    try {
      JSONObject err = new JSONObject();
      err.put("code", code);
      err.put("message", message == null ? "" : message);
      CanopyHostJni.resolveModule(callId, err.toString(), "");
    } catch (Exception e) {
      CanopyHostJni.resolveModule(callId, "{\"code\":\"rejected\"}", "");
    }
  }

  private BrightnessModule() {}
}
