// DeviceInfoModule.java — generated by `canopy-native gen-capability`.
//
// A JniModule("DeviceInfo") capability: __canopy_call("DeviceInfo", method, …)
// routes to invoke() here. Registered at boot (see the printed registration line). Reads static
// android.os.Build facts — no permission, no I/O — so it resolves SYNCHRONOUSLY inside invoke
// (no thread hop). Wire contract (must match Native/DeviceInfo.can):
//   info {} -> {model, manufacturer, systemVersion, sdkInt}
package com.canopyhost.modules;

import com.canopyhost.CanopyHostJni;

import org.json.JSONObject;

public final class DeviceInfoModule {

  public static void invoke(String method, String argsJson, String callId) {
    try {
      JSONObject args = new JSONObject(argsJson == null || argsJson.isEmpty() ? "{}" : argsJson);
      switch (method) {
        case "info": {
          JSONObject out = new JSONObject();
          out.put("model", str(android.os.Build.MODEL));
          out.put("manufacturer", str(android.os.Build.MANUFACTURER));
          out.put("systemVersion", str(android.os.Build.VERSION.RELEASE));
          out.put("sdkInt", android.os.Build.VERSION.SDK_INT);
          resolve(callId, out.toString());
          break;
        }
        default:
          reject(callId, "module_not_found", "DeviceInfo." + method);
      }
    } catch (Throwable t) {
      reject(callId, "rejected", t.getClass().getSimpleName()
          + (t.getMessage() != null ? ": " + t.getMessage() : ""));
    }
  }

  private static String str(String s) {
    return s == null ? "" : s;
  }

  private static void resolve(String callId, String resultJson) {
    CanopyHostJni.resolveModule(callId, "", resultJson);
  }

  private static void reject(String callId, String code, String message) {
    try {
      JSONObject err = new JSONObject();
      err.put("code", code);
      err.put("message", message == null ? "" : message);
      CanopyHostJni.resolveModule(callId, err.toString(), "");
    } catch (Exception e) {
      CanopyHostJni.resolveModule(callId, "{\"code\":\"rejected\"}", "");
    }
  }

  private DeviceInfoModule() {}
}
