// NetInfoModule.java — generated by `canopy-native gen-capability`, filled to working.
//
// A JniModule("NetInfo") capability: __canopy_call("NetInfo", method, …)
// routes to invoke() here. Registered at boot (see CanopyHostJni.cpp registerModule line).
//
// Wire contract (must match Native/NetInfo.can):
//   status {} -> {"connected":<bool>,"kind":"<string>"}   kind ∈ wifi|cellular|ethernet|none
//
// Reading connectivity is a fast, thread-safe ConnectivityManager query — resolve SYNCHRONOUSLY
// inside invoke (no main-looper hop needed). Requires android.permission.ACCESS_NETWORK_STATE.
package com.canopyhost.modules;

import android.content.Context;
import android.net.ConnectivityManager;
import android.net.Network;
import android.net.NetworkCapabilities;

import com.canopyhost.CanopyHostJni;
import com.canopyhost.MainActivity;

import org.json.JSONObject;

public final class NetInfoModule {

  public static void invoke(String method, String argsJson, String callId) {
    try {
      JSONObject args = new JSONObject(argsJson == null || argsJson.isEmpty() ? "{}" : argsJson);
      switch (method) {
        case "status": {
          boolean connected = false;
          String kind = "none";
          Context ctx = MainActivity.appContext();
          if (ctx != null) {
            ConnectivityManager cm =
                (ConnectivityManager) ctx.getSystemService(Context.CONNECTIVITY_SERVICE);
            if (cm != null) {
              Network n = cm.getActiveNetwork();
              NetworkCapabilities c = (n == null) ? null : cm.getNetworkCapabilities(n);
              if (c != null) {
                connected = c.hasCapability(NetworkCapabilities.NET_CAPABILITY_INTERNET);
                if (c.hasTransport(NetworkCapabilities.TRANSPORT_WIFI)) {
                  kind = "wifi";
                } else if (c.hasTransport(NetworkCapabilities.TRANSPORT_CELLULAR)) {
                  kind = "cellular";
                } else if (c.hasTransport(NetworkCapabilities.TRANSPORT_ETHERNET)) {
                  kind = "ethernet";
                }
              }
            }
          }
          JSONObject out = new JSONObject();
          out.put("connected", connected);
          out.put("kind", kind);
          android.util.Log.i("Canopy",
              "NetInfo.status connected=" + connected + " kind=" + kind + " — generated capability ran");
          resolve(callId, out.toString());
          break;
        }
        default:
          reject(callId, "module_not_found", "NetInfo." + method);
      }
    } catch (Throwable t) {
      reject(callId, "rejected", t.getClass().getSimpleName()
          + (t.getMessage() != null ? ": " + t.getMessage() : ""));
    }
  }

  private static void resolve(String callId, String resultJson) {
    CanopyHostJni.resolveModule(callId, "", resultJson);
  }

  private static void reject(String callId, String code, String message) {
    try {
      JSONObject err = new JSONObject();
      err.put("code", code);
      err.put("message", message == null ? "" : message);
      CanopyHostJni.resolveModule(callId, err.toString(), "");
    } catch (Exception e) {
      CanopyHostJni.resolveModule(callId, "{\"code\":\"rejected\"}", "");
    }
  }

  private NetInfoModule() {}
}
