// VibrationModule.java — generated by `canopy-native gen-capability`.
//
// A JniModule("Vibration") capability: __canopy_call("Vibration", method, …)
// routes to invoke() here. Registered at boot (see the printed registration line). Each method
// stub resolves null — fill in the body using `args`, and hop to a worker/main thread as the
// API requires (HttpModule runs off-thread; PlatformModule posts to the main looper).
package com.canopyhost.modules;

import com.canopyhost.CanopyHostJni;

import org.json.JSONObject;

public final class VibrationModule {

  public static void invoke(String method, String argsJson, String callId) {
    try {
      JSONObject args = new JSONObject(argsJson == null || argsJson.isEmpty() ? "{}" : argsJson);
      switch (method) {
        case "vibrate": {
          long ms = args.optLong("ms", 200L);
          android.os.Vibrator vib = vibrator();
          if (vib != null) {
            if (android.os.Build.VERSION.SDK_INT >= 26) {
              vib.vibrate(android.os.VibrationEffect.createOneShot(ms, android.os.VibrationEffect.DEFAULT_AMPLITUDE));
            } else {
              vib.vibrate(ms);
            }
          }
          android.util.Log.i("Canopy", "Vibration.vibrate(" + ms + "ms) — generated capability ran");
          resolve(callId, "null");
          break;
        }
        case "cancel": {
          android.os.Vibrator vib = vibrator();
          if (vib != null) { vib.cancel(); }
          android.util.Log.i("Canopy", "Vibration.cancel — generated capability ran");
          resolve(callId, "null");
          break;
        }
        default:
          reject(callId, "module_not_found", "Vibration." + method);
      }
    } catch (Throwable t) {
      reject(callId, "rejected", t.getClass().getSimpleName()
          + (t.getMessage() != null ? ": " + t.getMessage() : ""));
    }
  }

  private static android.os.Vibrator vibrator() {
    android.content.Context c = com.canopyhost.MainActivity.appContext();
    return c == null ? null
        : (android.os.Vibrator) c.getSystemService(android.content.Context.VIBRATOR_SERVICE);
  }

  private static void resolve(String callId, String resultJson) {
    CanopyHostJni.resolveModule(callId, "", resultJson);
  }

  private static void reject(String callId, String code, String message) {
    try {
      JSONObject err = new JSONObject();
      err.put("code", code);
      err.put("message", message == null ? "" : message);
      CanopyHostJni.resolveModule(callId, err.toString(), "");
    } catch (Exception e) {
      CanopyHostJni.resolveModule(callId, "{\"code\":\"rejected\"}", "");
    }
  }

  private VibrationModule() {}
}