// CanopyHostJni.cpp — JNI glue: forwards the C++ __fabric_* installer to the Java
// CanopyHost, and routes Hermes boot + event emission.
//
// This is the Android counterpart of the iOS CanopyHostViewController.mm boot flow. It
// owns the Hermes runtime and a CanopyHost C++ shim that calls Java methods over JNI.
//
// Integration template (Android NDK + Hermes). Reference-level: the exact Hermes
// runtime factory + thread/Looper plumbing depend on your RN version. The seams are
// marked TODO.

#include <jni.h>
#include <functional>
#include <memory>
#include <mutex>
#include <string>
#include <unordered_map>

#include <hermes/hermes.h>
#include "CanopyAbiGate.h"   // RNV-2: boot-time Hermes/JSI ABI gate (bytecode version vs. the pin)
#include "CanopyFabric.h"    // from host/shared/cpp (add that dir to the NDK include path)
#include "CanopyModules.h"   // C1: the __canopy_* native-module ABI
#include "CanopyBlobs.h"     // C1: opaque binary-handle registry
#include "EchoModule.h"      // C1: the reference capability
#include "CanopyJni.h"            // Foundation: jniSetJavaVM, globalBlobRegistry, JniModule, resolveModule, blob bridge
#include "CanopyImage.h"          // canopy/image helpers
#include "RestoreEngineModule.h"  // canopy/inference: ORT NativeModule
#include "BillingModule.h"        // canopy/billing: C++ streaming NativeModule (entitlement Sub)
#include "StreamingJniModule.h"   // canopy/navigation: generic streaming wrapper (Lifecycle/AppShell)
#include <android/log.h>          // console polyfill sink

// Autolinked capability registrant — GENERATED by `canopy-native` from the dependency graph
// (tool/src/Canopy/Native/Autolink.hs), the native analogue of the web compiler bundling each
// package's external/*.js. Guarded by __has_include so an un-autolinked checkout still compiles
// (the file only exists after a `canopy-native build`); when present, its registerModule() calls
// are how a NEW capability registers with ZERO edits to this host file — see canopyRegister... below.
#if __has_include("generated/CanopyGeneratedRegistrant.h")
#include "generated/CanopyGeneratedRegistrant.h"
#define CANOPY_HAS_GENERATED_REGISTRANT 1
#endif

using namespace canopy;
using namespace facebook;

namespace {

JavaVM* g_vm = nullptr;
jobject g_javaHost = nullptr;                  // global ref to the Java CanopyHost
std::unique_ptr<jsi::Runtime> g_runtime;        // the Hermes runtime (owned on the JS thread)
std::shared_ptr<ModuleRegistry> g_registry;     // C1: native-module dispatcher
std::shared_ptr<BlobRegistry> g_blobs;          // C1: binary side-table (aliased to globalBlobRegistry)
std::shared_ptr<canopy::RestoreEngineModule> g_restoreEngine;  // inference: holds the ORT model bytes

// DEV-4 in-process reload state. boot() creates the host RCTRootView ONCE and caches its handle +
// the boot flags here; reload() re-boots onto the SAME cached root (so the host view tree under the
// surface is preserved — no flicker, no fresh process) with the SAME flags. -1 = "never booted".
Handle g_rootTag = -1;
std::string g_bootFlags = "{}";

// postToJs plumbing: a native callback table keyed by id + the Java static that posts a
// Runnable onto the JS-thread Looper. See postToJs() / runJsCallback() below.
jclass g_jniClass = nullptr;                    // global ref to CanopyHostJni
jmethodID g_scheduleOnJs = nullptr;             // CanopyHostJni.scheduleOnJs(long)
jmethodID g_onJsError = nullptr;                // CanopyHostJni.onJsError(String,String,boolean)

// Route a JS/native error to the red-box instead of letting it escape into Hermes' frame
// (which std::terminate()s → SIGABRT). Called from the guards at every host↔JS re-entry site.
void reportJsError(JNIEnv* e, const std::string& msg, const std::string& stack, bool fatal) {
  if (!e || !g_jniClass || !g_onJsError) return;
  jstring jmsg = e->NewStringUTF(msg.c_str());
  jstring jstack = e->NewStringUTF(stack.c_str());
  e->CallStaticVoidMethod(g_jniClass, g_onJsError, jmsg, jstack, (jboolean)fatal);
  e->DeleteLocalRef(jmsg);
  e->DeleteLocalRef(jstack);
}

// Best-effort: rewrite a Hermes stack's `canopy.bundle.js:LINE:COL` frames to `.can` source
// via the JS-side source-map symbolicator the walker installs (globalThis.__canopy_symbolicate,
// fed the in-bundle map in dev). On any failure — no map (release), function not yet installed
// (a pre-program boot throw), or a re-entry exception — returns the raw stack untouched, so
// symbolication never masks the underlying error. Runs on the JS thread (the guards do), so
// touching g_runtime is safe.
std::string symbolicateStack(const std::string& stack) {
  if (!g_runtime || stack.empty()) return stack;
  try {
    jsi::Runtime& rt = *g_runtime;
    jsi::Value fn = rt.global().getProperty(rt, "__canopy_symbolicate");
    if (!fn.isObject() || !fn.getObject(rt).isFunction(rt)) return stack;
    jsi::Value res = fn.getObject(rt).getFunction(rt).call(rt, jsi::String::createFromUtf8(rt, stack));
    if (res.isString()) return res.getString(rt).utf8(rt);
  } catch (...) { /* best-effort — fall through to the raw stack */ }
  return stack;
}

// RNV-2 boot-time ABI gate. Reads the LIVE Hermes ABI off the runtime the host just created
// (HermesRuntime::getBytecodeVersion() — a static on the LINKED engine — and the VM description)
// and compares it to the pin baked from host/vendor.lock.json (canopy::checkHermesAbi). On a
// mismatch the vendored libhermes.so does not match its pinned JSI headers: it would boot here
// and corrupt/SIGABRT on a real device (risk R1). We fail LOUD:
//   • always emit a FATAL-level __android_log line (survives release, no UI needed); and
//   • route the same message to the red-box (reportJsError, fatal=true) — the dev-visible
//     overlay in debug, harmless-but-logged in release.
// Returns true when the ABI matches (boot proceeds), false on mismatch (caller aborts boot
// before evaluating the bundle — a mismatched engine must not run user JS).
bool enforceHermesAbiGate(JNIEnv* e, jsi::Runtime& rt) {
  const int liveBytecode = static_cast<int>(facebook::hermes::HermesRuntime::getBytecodeVersion());
  std::string vmDesc;
  try {
    vmDesc = rt.description();
  } catch (...) {
    vmDesc = "<unavailable>";
  }
  canopy::AbiCheckResult res = canopy::checkHermesAbi(liveBytecode, vmDesc);
  if (res.ok) {
    __android_log_print(ANDROID_LOG_INFO, "CanopyAbiGate", "%s", res.message.c_str());
    return true;
  }
  // Fail-closed. FATAL log first (the only signal in a release build with no dev overlay), then
  // the red-box path so a debug boot stops on a visible screen instead of a later silent crash.
  __android_log_print(ANDROID_LOG_FATAL, "CanopyAbiGate", "%s", res.message.c_str());
  reportJsError(e, res.message, /*stack=*/"Hermes/JSI ABI gate (RNV-2)", /*fatal=*/true);
  return false;
}

// Wrap a JS↔host re-entry; on a JS or native exception, report it (red-box) instead of crash.
template <typename F>
bool guardJsCall(JNIEnv* e, const char* site, bool fatal, F&& fn) {
  try {
    fn();
    return true;
  } catch (facebook::jsi::JSError& err) {
    reportJsError(e, std::string(site) + ": " + err.getMessage(), symbolicateStack(err.getStack()), fatal);
  } catch (const std::exception& ex) {
    reportJsError(e, std::string(site) + " (native): " + ex.what(), "", true);
  } catch (...) {
    reportJsError(e, std::string(site) + " (unknown native exception)", "", true);
  }
  return false;
}
std::mutex g_cbMu;
std::unordered_map<jlong, std::function<void()>> g_callbacks;
jlong g_nextCb = 1;

JNIEnv* env() {
  JNIEnv* e = nullptr;
  g_vm->AttachCurrentThread(&e, nullptr);
  return e;
}

// The C1 worker→JS-thread hop (plan C1 §3.5). Replaces the old inline requestFrame: a
// completion produced on a worker thread is parked in g_callbacks and scheduled onto the
// CanopyJS Looper via Java; runJsCallback() then runs it ON the JS thread, where g_runtime
// lives. Getting this wrong (touching the runtime from the worker thread) is a hard crash.
void postToJs(std::function<void()> fn) {
  jlong id;
  {
    std::lock_guard<std::mutex> g(g_cbMu);
    id = g_nextCb++;
    g_callbacks[id] = std::move(fn);
  }
  JNIEnv* e = env();
  e->CallStaticVoidMethod(g_jniClass, g_scheduleOnJs, id);
}

// Call a Java CanopyHost method returning int, with (String,String) or (int,...) args.
jclass hostClass(JNIEnv* e) { return e->GetObjectClass(g_javaHost); }

// A CanopyHost C++ shim that forwards every call to the Java object. Only the shapes
// matter here; the Java side (CanopyHost.java) does the real UI work.
class JavaBackedHost : public CanopyHost {
 public:
  Handle createView(const std::string& name, const std::string& props) override {
    JNIEnv* e = env();
    jmethodID m = e->GetMethodID(hostClass(e), "createView", "(Ljava/lang/String;Ljava/lang/String;)I");
    return e->CallIntMethod(g_javaHost, m, e->NewStringUTF(name.c_str()), e->NewStringUTF(props.c_str()));
  }
  void updateProps(Handle h, const std::string& props) override {
    JNIEnv* e = env();
    jmethodID m = e->GetMethodID(hostClass(e), "updateProps", "(ILjava/lang/String;)V");
    e->CallVoidMethod(g_javaHost, m, h, e->NewStringUTF(props.c_str()));
  }
  // __fabric_updatePropScalar(handle, key, value) — the AND-8 single-scalar fast path. Forwards
  // (int, String, String) over JNI exactly like command(), but the Java side does the work with NO
  // `new JSONObject` (CanopyHost.updatePropScalar). This is the JSON-decode cost the fast path
  // eliminates on the Java side; everything object/style/null-shaped still rides updateProps above.
  void updatePropScalar(Handle h, const std::string& key, const std::string& value) override {
    JNIEnv* e = env();
    jmethodID m = e->GetMethodID(hostClass(e), "updatePropScalar",
                                 "(ILjava/lang/String;Ljava/lang/String;)V");
    jstring jkey = e->NewStringUTF(key.c_str());
    jstring jvalue = e->NewStringUTF(value.c_str());
    e->CallVoidMethod(g_javaHost, m, h, jkey, jvalue);
    e->DeleteLocalRef(jkey);
    e->DeleteLocalRef(jvalue);
  }
  void insertChild(Handle p, Handle c, int i) override { call3("insertChild", p, c, i); }
  void removeChild(Handle p, Handle c, int i) override { call3("removeChild", p, c, i); }
  void setRoot(Handle h) override {
    JNIEnv* e = env();
    e->CallVoidMethod(g_javaHost, e->GetMethodID(hostClass(e), "setRoot", "(I)V"), h);
  }
  void setEvents(Handle h, const std::string& names) override {
    JNIEnv* e = env();
    jmethodID m = e->GetMethodID(hostClass(e), "setEvents", "(ILjava/lang/String;)V");
    e->CallVoidMethod(g_javaHost, m, h, e->NewStringUTF(names.c_str()));
  }
  // __fabric_command(handle, name, argsJson) — the AND-3/IOS-8 imperative-op seam. Forwards
  // over JNI exactly like updateProps; the Java side runs the op and emits its result back via
  // CanopyHostJni.emitEvent(handle, "__commandResult", resultJson) (the same emit path press
  // uses). AND-3's Java command() is a trivial echo; focus/measure/scrollTo are AND-4.
  void command(Handle h, const std::string& name, const std::string& argsJson) override {
    JNIEnv* e = env();
    jmethodID m = e->GetMethodID(hostClass(e), "command",
                                 "(ILjava/lang/String;Ljava/lang/String;)V");
    jstring jname = e->NewStringUTF(name.c_str());
    jstring jargs = e->NewStringUTF(argsJson.c_str());
    e->CallVoidMethod(g_javaHost, m, h, jname, jargs);
    e->DeleteLocalRef(jname);
    e->DeleteLocalRef(jargs);
  }
  void requestFrame(std::function<void()> cb) override {
    // Route through the same JS-thread hop as module completions (C1 §3.5). A
    // Choreographer-driven vsync post is the later refinement; the thread-hop correctness
    // (never invoke the runtime off the JS thread) is what matters and is shared here.
    postToJs(std::move(cb));
  }
 private:
  void call3(const char* name, int a, int b, int c) {
    JNIEnv* e = env();
    e->CallVoidMethod(g_javaHost, e->GetMethodID(hostClass(e), name, "(III)V"), a, b, c);
  }
};

std::shared_ptr<CanopyHost> g_host;

}  // namespace

extern "C" {

JNIEXPORT jint JNI_OnLoad(JavaVM* vm, void*) {
  g_vm = vm;
  canopy::jniSetJavaVM(vm);  // share the VM with the portable CanopyJni TU (JniModule + blob bridge)
  return JNI_VERSION_1_6;
}

JNIEXPORT void JNICALL
Java_com_canopyhost_CanopyHostJni_install(JNIEnv* e, jclass jniClass, jobject javaHost) {
  g_javaHost = e->NewGlobalRef(javaHost);
  g_host = std::make_shared<JavaBackedHost>();
  // Cache the CanopyHostJni class + scheduleOnJs(long) so postToJs can schedule onto the
  // JS-thread Looper from native (and from worker threads, via env()).
  g_jniClass = (jclass)e->NewGlobalRef(jniClass);
  g_scheduleOnJs = e->GetStaticMethodID(jniClass, "scheduleOnJs", "(J)V");
  g_onJsError = e->GetStaticMethodID(jniClass, "onJsError", "(Ljava/lang/String;Ljava/lang/String;Z)V");
}

// Minimal `console` polyfill. Bare Hermes ships no `console` global (React Native installs one
// from JS); the compiled Canopy bundle's effect-manager runtime references it, so install
// log/info/warn/error/debug/trace → __android_log under the "CanopyJS" tag.
static void installConsole(jsi::Runtime& rt) {
  auto logger = [](int prio) {
    return [prio](jsi::Runtime& rt, const jsi::Value&, const jsi::Value* args,
                  size_t count) -> jsi::Value {
      std::string line;
      for (size_t i = 0; i < count; i++) {
        if (i) line += " ";
        try {
          line += args[i].toString(rt).utf8(rt);
        } catch (...) {
          line += "<?>";
        }
      }
      __android_log_print(prio, "CanopyJS", "%s", line.c_str());
      return jsi::Value::undefined();
    };
  };
  jsi::Object console(rt);
  struct Method { const char* name; int prio; };
  const Method methods[] = {
      {"log", ANDROID_LOG_INFO},    {"info", ANDROID_LOG_INFO},
      {"warn", ANDROID_LOG_WARN},   {"error", ANDROID_LOG_ERROR},
      {"debug", ANDROID_LOG_DEBUG}, {"trace", ANDROID_LOG_VERBOSE},
  };
  for (const Method& m : methods) {
    console.setProperty(
        rt, m.name,
        jsi::Function::createFromHostFunction(
            rt, jsi::PropNameID::forAscii(rt, m.name), 1, logger(m.prio)));
  }
  rt.global().setProperty(rt, "console", console);
}

// RNV-7 load-time gate: before handing a bundle buffer to Hermes, check that — IF it is a real
// .hbc — its stamped bytecode-format version equals the vendored engine pin (the load-time half of
// the RNV-2 contract; checkBundleBytecode is a no-op for plain JS source). A mismatch means the
// .hbc was compiled by a hermesc whose HBC format differs from the linked engine: the engine would
// reject it. We fail LOUD (fatal log + red-box) and bail BEFORE evaluation, exactly like the engine
// ABI gate. Returns true when the buffer is safe to evaluate.
bool enforceBundleBytecodeGate(JNIEnv* e, const std::string& bundle) {
  canopy::AbiCheckResult res = canopy::checkBundleBytecode(
      reinterpret_cast<const uint8_t*>(bundle.data()), bundle.size());
  if (res.ok) {
    __android_log_print(ANDROID_LOG_INFO, "CanopyAbiGate", "%s", res.message.c_str());
    return true;
  }
  __android_log_print(ANDROID_LOG_FATAL, "CanopyAbiGate", "%s", res.message.c_str());
  reportJsError(e, res.message, /*stack=*/"Hermes .hbc load gate (RNV-7)", /*fatal=*/true);
  return false;
}

JNIEXPORT void JNICALL
Java_com_canopyhost_CanopyHostJni_boot(JNIEnv* e, jclass, jbyteArray bundle, jstring flagsJson) {
  // THREADING (C1 §3.5, direct-views host): the JS thread IS the main/UI thread — the same
  // posture as the iOS template — because every __fabric_* mount call touches android.view,
  // which must run on the UI thread. So g_runtime is created + owned here on the UI thread,
  // and postToJs's Looper is the main Looper (CanopyHostJni.jsHandler). Heavy module work
  // runs on its OWN worker thread (e.g. EchoModule's std::thread) and hops its completion
  // back via postToJs → main Looper → __canopy_resolve. (A future RN-Fabric-mount host could
  // move JS to a dedicated thread and marshal mounts to the UI thread; only postToJs changes.)
  //
  // RNV-7: the bundle arrives as RAW BYTES (jbyteArray), not a UTF-8 jstring, so a real Hermes
  // .hbc (binary bytecode) survives the JNI boundary intact. Hermes' evaluateJavaScript detects
  // the HBC magic and runs bytecode directly (no parse); plain JS source still evaluates as before.
  jsize bundleLen = e->GetArrayLength(bundle);
  std::string srcStr;
  srcStr.resize(static_cast<size_t>(bundleLen));
  if (bundleLen > 0) {
    e->GetByteArrayRegion(bundle, 0, bundleLen, reinterpret_cast<jbyte*>(&srcStr[0]));
  }
  const char* flags = e->GetStringUTFChars(flagsJson, nullptr);

  // Fully qualified: with `using namespace facebook;` and the real Hermes headers (which
  // also declare a top-level ::hermes VM namespace), bare `hermes::` is ambiguous.
  g_runtime = facebook::hermes::makeHermesRuntime();

  // RNV-2: gate the linked Hermes/JSI ABI against the vendored pin BEFORE installing anything or
  // evaluating the bundle. A mismatched libhermes must never run user JS — it boots fine here and
  // corrupts on a real device. Fail-closed: log fatal + red-box, then bail out of boot.
  if (!enforceHermesAbiGate(e, *g_runtime)) {
    g_runtime.reset();
    e->ReleaseStringUTFChars(flagsJson, flags);
    return;
  }

  // RNV-7: gate the BUNDLE's bytecode version (if it is a real .hbc) against the same engine pin,
  // also BEFORE evaluation — a wrong-toolchain .hbc would be rejected by Hermes mid-eval otherwise.
  if (!enforceBundleBytecodeGate(e, srcStr)) {
    g_runtime.reset();
    e->ReleaseStringUTFChars(flagsJson, flags);
    return;
  }

  installCanopyFabric(*g_runtime, g_host);

  // C1: install the native-module ABI and register capabilities. The registry holds the
  // runtime + the postToJs hop; async results re-enter Hermes only through that hop.
  // Alias g_blobs to the ONE process-wide registry the blob bridge + CanopyBitmap renderer +
  // ORT all share (a handle minted in ImageModule.decode is the same one ORT + the renderer see).
  g_blobs = std::shared_ptr<BlobRegistry>(&canopy::globalBlobRegistry(), [](BlobRegistry*){});
  g_registry = std::make_shared<ModuleRegistry>();
  g_registry->setRuntime(g_runtime.get());
  g_registry->setPostToJs(postToJs);
  installCanopyModules(*g_runtime, g_registry);
  g_registry->registerModule(std::make_shared<EchoModule>());  // C1 first-light capability

  // Pure-Java JniModule capabilities (reuse canopy::JniModule via CanopyJni.cpp -> Java bridges).
  g_registry->registerModule(std::make_shared<canopy::JniModule>("Image"));
  g_registry->registerModule(std::make_shared<canopy::JniModule>("Photos"));
  g_registry->registerModule(std::make_shared<canopy::JniModule>("Album"));
  g_registry->registerModule(std::make_shared<canopy::JniModule>("ShareImage"));
  g_registry->registerModule(std::make_shared<canopy::JniModule>("StorageSecure"));
  g_registry->registerModule(std::make_shared<canopy::JniModule>("Notify"));
  g_registry->registerModule(std::make_shared<canopy::JniModule>("Http"));  // fetch-equivalent (HttpURLConnection)
  g_registry->registerModule(std::make_shared<canopy::JniModule>("Platform"));  // Linking + Clipboard
  g_registry->registerModule(std::make_shared<canopy::JniModule>("Vibration"));  // generated via `canopy-native gen-capability`
  // The Expo-comparable fan-out, all scaffolded by `canopy-native gen-capability`:
  g_registry->registerModule(std::make_shared<canopy::JniModule>("Battery"));
  g_registry->registerModule(std::make_shared<canopy::JniModule>("DeviceInfo"));
  g_registry->registerModule(std::make_shared<canopy::JniModule>("NetInfo"));
  g_registry->registerModule(std::make_shared<canopy::JniModule>("Haptics"));
  g_registry->registerModule(std::make_shared<canopy::JniModule>("Brightness"));
  // C++ NativeModule: ORT inference (the model bytes arrive via setRestoreEngineModel after boot).
  g_restoreEngine = std::make_shared<canopy::RestoreEngineModule>();
  g_registry->registerModule(g_restoreEngine);

  // Effect modules with live subscriptions — NOT plain JniModules (jniResolve erases the row on
  // the first resolve, so a Sub cannot ride it). canopy/billing is a bespoke C++ streaming
  // module; canopy/navigation's Lifecycle + AppShell ride the generic StreamingJniModule. The
  // Java sides (BillingModule / Lifecycle / AppShell) push events into THESE global instances
  // via BillingModule.nativeEmit / StreamingBridge.nativeEmit. One-shot Cmds (getProducts,
  // purchase, restore, setStatusBarStyle, allowDefaultBack) delegate to Java like any JniModule.
  g_registry->registerModule(canopy::globalBillingModule());
  g_registry->registerModule(
      canopy::globalStreamingModule("Lifecycle", {"appState", "memoryPressure", "backPressed"}));
  g_registry->registerModule(canopy::globalStreamingModule("AppShell", {"colorScheme"}));

#ifdef CANOPY_HAS_GENERATED_REGISTRANT
  // Autolinked capability modules: every native module a dependency DECLARES in its canopy.json
  // "native" block, registered without a per-capability edit to THIS file. The block above is the
  // legacy hand-maintained set (migrating into their packages); new capabilities go through here.
  canopy::canopyRegisterGeneratedModules(*g_registry);
#endif

  // Bare Hermes has no `console`; the bundle's runtime references it. Install before eval.
  installConsole(*g_runtime);

  // Guarded boot: a bundle syntax error, a missing main module, or a throw inside the first
  // synchronous view(model) becomes a red-box (fatal: there is no running program), not SIGABRT.
  // srcStr was filled from the jbyteArray above — for a real .hbc it holds binary bytecode, which
  // Hermes' evaluateJavaScript runs directly (isHermesBytecode); for JS source it parses as before.
  std::string flagsStr(flags);
  g_bootFlags = flagsStr;  // cached for a later in-process reload (re-boot with the same flags)
  // Name the eval source after the actual bundle kind so a Hermes stack/log is unambiguous.
  const char* sourceUrl =
      canopy::looksLikeHermesBytecode(reinterpret_cast<const uint8_t*>(srcStr.data()), srcStr.size())
          ? "canopy.bundle.hbc"
          : "canopy.bundle.js";
  guardJsCall(e, "boot", /*fatal=*/true, [&]() {
    g_runtime->evaluateJavaScript(
        std::make_shared<jsi::StringBuffer>(srcStr), sourceUrl);
    // Create the host root ONCE and cache it; reload() re-boots onto this same handle so the
    // surface's root view (and the rest of the host view tree it anchors) is preserved.
    g_rootTag = g_host->createView("RCTRootView", "{\"style\":{\"flex\":\"1\"}}");
    canopyBoot(*g_runtime, g_rootTag, flagsStr);
  });

  e->ReleaseStringUTFChars(flagsJson, flags);
}

// DEV-4 — call a 0-arg JS reload-seam function on the live runtime, returning whether it ran and
// reported true. The seam (native.js: __canopy_captureState / __canopy_teardown) is published only
// by a BOOTED debug program; if it is absent (a release bundle, or a never-booted runtime) this is a
// no-op returning false, so reload() degrades to a clean re-eval. Runs on the JS thread (the caller
// guarantees it), so touching g_runtime is safe.
bool callReloadSeam(jsi::Runtime& rt, const char* name) {
  jsi::Value fn = rt.global().getProperty(rt, name);
  if (!fn.isObject() || !fn.getObject(rt).isFunction(rt)) return false;
  jsi::Value res = fn.getObject(rt).getFunction(rt).call(rt);
  return res.isBool() && res.getBool();
}

// Run a parked postToJs callback. Java's scheduleOnJs posted this onto the CanopyJS Looper,
// so we are now ON the JS thread — safe to touch g_runtime (canopyResolveCall runs here).
JNIEXPORT void JNICALL
Java_com_canopyhost_CanopyHostJni_runJsCallback(JNIEnv* e, jclass, jlong id) {
  std::function<void()> fn;
  {
    std::lock_guard<std::mutex> g(g_cbMu);
    auto it = g_callbacks.find(id);
    if (it == g_callbacks.end()) { return; }
    fn = std::move(it->second);
    g_callbacks.erase(it);
  }
  // The highest-frequency re-entry: every Cmd/Sub completion + event re-enters update/view
  // here. A throw in the app's update/view (or a decoder) becomes a red-box, not a SIGABRT.
  if (fn) { guardJsCall(e, "callback", /*fatal=*/false, [&]() { fn(); }); }
}

JNIEXPORT void JNICALL
Java_com_canopyhost_CanopyHostJni_emitEvent(JNIEnv* e, jclass, jint handle, jstring name, jstring payload) {
  const char* n = e->GetStringUTFChars(name, nullptr);
  const char* p = e->GetStringUTFChars(payload, nullptr);
  std::string nStr(n), pStr(p);
  // A throw in the press/gesture handler (update) becomes a red-box, not a SIGABRT.
  if (g_runtime) {
    guardJsCall(e, "event", /*fatal=*/false, [&]() {
      canopyEmitEvent(*g_runtime, handle, nStr, pStr);
    });
  }
  e->ReleaseStringUTFChars(name, n);
  e->ReleaseStringUTFChars(payload, p);
}

// DEV-4 — in-process, state-preserving reload (the dev-loop's edit→see cycle without a fresh
// process). Re-evaluates the new bundle on the SAME Hermes runtime and re-boots onto the SAME cached
// root, preserving the host view tree (only the program's mounted subtree under the root is rebuilt)
// and the user's TEA model. This is the host half of the DEV-2 reload seam (native.js owns the JS
// half: __canopy_captureState / __canopy_teardown / __canopy_remount). Must run on the JS/UI thread
// (Java posts it onto the JS Looper before calling), where g_runtime lives.
//
// Sequence (mirrors harness/run-reload-seam.js, which drives this exact loop device-free):
//   1. captureState() — read the live TEA model so it survives the new-bundle eval (an opaque
//      { model } carrier; null in a release bundle / a never-booted runtime → a cold reload).
//   2. teardown()     — stop the running Subs (so the reload does not double-subscribe) and release
//      THIS program's mounted subtree under the cached root, leaving a clean root view.
//   3. clear globalThis.Elm + scope.Elm — the host's reset step: the compiler's _Platform_export
//      rejects a duplicate Elm.Main on the same runtime, so a re-eval must clear it first (DEV-4's
//      plan note: "verify IIFE re-eval is idempotent; fall back to clean in-process reboot if not").
//   4. evaluateJavaScript(newBundle) — re-eval on the SAME runtime (same modules, same console/ABI).
//   5. __canopy_boot(cachedRootTag, flags) — re-boot onto the SAME root handle (host view preserved).
//   6. remount(captured) — restore the captured model into the freshly-booted program (the user
//      lands back where they were — the whole point vs. a cold restart).
//
// Guarded end-to-end: a syntax error / throw in the NEW bundle becomes a red-box (fatal: the old
// program is already torn down, so there is no running program to fall back to), not a SIGABRT.
//
// Bound to CanopyHost.nativeReload (a static native) — the reload ENTRY lives on the mount object
// (CanopyHost) that owns the host view tree this preserves, while boot/install/emit stay on
// CanopyHostJni. libcanopyhost.so is already loaded (CanopyHostJni's static block) before any
// CanopyHost exists, so resolving this symbol off CanopyHost is safe.
JNIEXPORT void JNICALL
Java_com_canopyhost_CanopyHost_nativeReload(JNIEnv* e, jclass, jstring newBundleJs) {
  if (!g_runtime || g_rootTag < 0) {
    // Never booted (or a boot that aborted at the ABI gate): nothing to reload onto. A red-box
    // explains it rather than silently doing nothing.
    reportJsError(e, "reload: no booted runtime to reload onto", "DEV-4 in-process reload", /*fatal=*/false);
    return;
  }
  const char* src = e->GetStringUTFChars(newBundleJs, nullptr);
  std::string srcStr(src ? src : "");
  e->ReleaseStringUTFChars(newBundleJs, src);

  guardJsCall(e, "reload", /*fatal=*/true, [&]() {
    jsi::Runtime& rt = *g_runtime;

    // (1) capture the live model (survives the new eval). The carrier is an opaque JS object the
    // walker minted; we hold it on the JS stack across the eval and thread it back into remount.
    jsi::Value captured = jsi::Value::null();
    {
      jsi::Value cap = rt.global().getProperty(rt, "__canopy_captureState");
      if (cap.isObject() && cap.getObject(rt).isFunction(rt)) {
        captured = cap.getObject(rt).getFunction(rt).call(rt);
      }
    }

    // (2) tear the live program down (stop Subs + release the mounted subtree under the root).
    callReloadSeam(rt, "__canopy_teardown");

    // (3) the host reset: clear Elm so _Platform_export accepts the re-eval's Elm.Main. We clear it
    // on the global and on `scope` (the compiler exports under either depending on the IIFE shape);
    // a missing property is harmless (setting it to undefined is idempotent).
    rt.global().setProperty(rt, "Elm", jsi::Value::undefined());
    {
      jsi::Value scope = rt.global().getProperty(rt, "scope");
      if (scope.isObject()) scope.getObject(rt).setProperty(rt, "Elm", jsi::Value::undefined());
    }

    // (4) re-evaluate the NEW bundle on the SAME runtime. The DEV-4 reload path carries JS SOURCE
    // (the dev loop pushes JS for a fast edit→see cycle — no hermesc round-trip); the .hbc bytecode
    // path is the baked-asset/production boot in Java_..._boot. evaluateJavaScript would run either.
    rt.evaluateJavaScript(std::make_shared<jsi::StringBuffer>(srcStr), "canopy.bundle.js (reload)");

    // (5) re-boot onto the SAME cached root handle (the host root view + surface are untouched) with
    // the SAME flags the program first booted with.
    canopyBoot(rt, g_rootTag, g_bootFlags);

    // (6) restore the captured model into the freshly-booted program. A null carrier (release bundle
    // / no live state) makes remount a no-op — the reloaded program just keeps its init model.
    jsi::Value rem = rt.global().getProperty(rt, "__canopy_remount");
    if (rem.isObject() && rem.getObject(rt).isFunction(rt)) {
      rem.getObject(rt).getFunction(rt).call(rt, captured);
    }
  });
}

// Hand the ORT model bytes (read from assets by MainActivity after boot) to the engine.
// (resolveModule + the nativeBlob* exports live in CanopyJni.cpp — do not redefine them here.)
JNIEXPORT void JNICALL
Java_com_canopyhost_CanopyHostJni_setRestoreEngineModel(JNIEnv* e, jclass, jbyteArray bytes) {
  if (!g_restoreEngine || bytes == nullptr) return;
  jsize n = e->GetArrayLength(bytes);
  jbyte* p = e->GetByteArrayElements(bytes, nullptr);
  g_restoreEngine->setModelBytes(reinterpret_cast<const uint8_t*>(p), (size_t)n);
  e->ReleaseByteArrayElements(bytes, p, JNI_ABORT);
}

}  // extern "C"
