// CanopyHostJni.cpp — JNI glue: forwards the C++ __fabric_* installer to the Java
// CanopyHost, and routes Hermes boot + event emission.
//
// This is the Android counterpart of the iOS CanopyHostViewController.mm boot flow. It
// owns the Hermes runtime and a CanopyHost C++ shim that calls Java methods over JNI.
//
// Integration template (Android NDK + Hermes). Reference-level: the exact Hermes
// runtime factory + thread/Looper plumbing depend on your RN version. The seams are
// marked TODO.

#include <jni.h>
#include <cstdint>
#include <functional>
#include <memory>
#include <mutex>
#include <string>
#include <unordered_map>
#include <vector>

#include <hermes/hermes.h>   // RNV-2 ABI gate ONLY: HermesRuntime::getBytecodeVersion() static read
#include "CanopyHermes.h"    // RNV-4: the ONE Hermes runtime factory (canopy::makeRuntime) — the seam
#include "CanopyAbiGate.h"   // RNV-2: boot-time Hermes/JSI ABI gate (bytecode version vs. the pin)
#include "CanopyFabric.h"    // from host/shared/cpp (add that dir to the NDK include path)
#include "CanopyModules.h"   // C1: the __canopy_* native-module ABI
#include "CanopyBlobs.h"     // C1: opaque binary-handle registry
#include "EchoModule.h"      // C1: the reference capability
#include "CanopyJni.h"            // Foundation: jniSetJavaVM, globalBlobRegistry, JniModule (Photos), resolveModule, blob bridge
#include "RestoreEngineModule.h"  // canopy/inference: ORT NativeModule (host-resident — model bytes after boot)
#include "CanopySignalFloor.h"    // REL-2 SIG: native hard-crash floor (installed off-by-default from Java)
#include <android/log.h>          // console polyfill sink
// NOTE (AUTO-E-DELETE): the per-capability impls (BillingModule.h / StreamingJniModule.h /
// CanopyImage.h, etc.) are no longer #included HERE — this file stopped naming any per-capability
// symbol. The autolinked capabilities are registered through the GENERATED registrant below, which
// #includes whatever package headers (e.g. BillingModule.h, StreamingJniModule.h) its own
// registerModule() calls need, from the package's native/cpp include dir.

// Autolinked capability registrant — GENERATED by `canopy-native` from the dependency graph
// (tool/src/Canopy/Native/Autolink.hs), the native analogue of the web compiler bundling each
// package's external/*.js. Guarded by __has_include so an un-autolinked checkout still compiles
// (the file only exists after a `canopy-native build`); when present, its registerModule() calls
// are how a NEW capability registers with ZERO edits to this host file — see canopyRegister... below.
#if __has_include("generated/CanopyGeneratedRegistrant.h")
#include "generated/CanopyGeneratedRegistrant.h"
// The generated CMake fragment (canopy-autolink.cmake) also defines this via
// add_compile_definitions when a C++ capability is autolinked; guard so the two paths don't
// collide with a -Wmacro-redefined warning (both define it to 1).
#ifndef CANOPY_HAS_GENERATED_REGISTRANT
#define CANOPY_HAS_GENERATED_REGISTRANT 1
#endif
#endif

using namespace canopy;
using namespace facebook;

namespace {

JavaVM* g_vm = nullptr;
jobject g_javaHost = nullptr;                  // global ref to the Java CanopyHost
std::unique_ptr<jsi::Runtime> g_runtime;        // the Hermes runtime (owned on the JS thread)
std::shared_ptr<ModuleRegistry> g_registry;     // C1: native-module dispatcher
std::shared_ptr<BlobRegistry> g_blobs;          // C1: binary side-table (aliased to globalBlobRegistry)
std::shared_ptr<canopy::RestoreEngineModule> g_restoreEngine;  // inference: holds the ORT model bytes

// DEV-4 in-process reload state. boot() creates the host RCTRootView ONCE and caches its handle +
// the boot flags here; reload() re-boots onto the SAME cached root (so the host view tree under the
// surface is preserved — no flicker, no fresh process) with the SAME flags. -1 = "never booted".
Handle g_rootTag = -1;
std::string g_bootFlags = "{}";

// postToJs plumbing: a native callback table keyed by id + the Java static that posts a
// Runnable onto the JS-thread Looper. See postToJs() / runJsCallback() below.
jclass g_jniClass = nullptr;                    // global ref to CanopyHostJni
jmethodID g_scheduleOnJs = nullptr;             // CanopyHostJni.scheduleOnJs(long)
jmethodID g_onJsError = nullptr;                // CanopyHostJni.onJsError(String,String,boolean)
jmethodID g_onReloadNotice = nullptr;           // CanopyHostJni.onReloadNotice(String,String) — DEV-8
jmethodID g_applyBatchOnUi = nullptr;           // CanopyHostJni.applyBatchOnUi(long) — RND-8

// RND-8 — off-UI-thread mode. When true, the Hermes runtime + the whole walker run on a DEDICATED
// "CanopyJS" thread (CanopyHostJni's HandlerThread), and a frame's view writes are marshalled to the
// UI thread as ONE flat binary batch per frame (see the BatchSink installed in boot()). When false
// (the default), the JS thread IS the UI thread — the historical single-thread posture — and every
// __fabric_* call mutates android.view inline. Resolved ONCE from the Java side at install() so the
// C++ and Java agree on the same mode (CanopyHostJni.jsOffUiThread()).
bool g_jsOffUiThread = false;

// RND-8 — the UI-thread batch side-table. The BatchSink runs on the JS thread; it COPIES the frame's
// flat binary buffer here (keyed by a monotonic id), then asks Java to post applyBatchOnUi(id) onto the
// UI Looper. runUiBatch(id) — on the UI thread — pulls the bytes back out and replays them against the
// host. Guarded by g_batchMu because the producer (JS thread) and the consumer (UI thread) are now
// genuinely different threads. Mirrors the g_callbacks pattern, but the payload is bytes, not a closure.
std::mutex g_batchMu;
std::unordered_map<jlong, std::vector<uint8_t>> g_pendingBatches;
jlong g_nextBatch = 1;

// RND-8 — how many frame batches the sink has marshalled to the UI thread. Used ONLY for the
// boot-time sanity check below: off-UI-thread mode REQUIRES a batching (RND-7) bundle, because a
// per-mutation bundle would call the host's android.view methods DIRECTLY on the CanopyJS thread (a
// CalledFromWrongThreadException once the views attach to the window). If the boot frame marshalled
// ZERO batches while off-UI-thread mode is on, the bundle is NOT batching and we fail LOUD with a clear
// message instead of crashing later with a confusing wrong-thread stack. Plain int (only read/written
// on the boot path + the JS thread); the lock on the side-table already orders the producer writes.
int g_batchesMarshalled = 0;

// Route a JS/native error to the red-box instead of letting it escape into Hermes' frame
// (which std::terminate()s → SIGABRT). Called from the guards at every host↔JS re-entry site.
void reportJsError(JNIEnv* e, const std::string& msg, const std::string& stack, bool fatal) {
  if (!e || !g_jniClass || !g_onJsError) return;
  jstring jmsg = e->NewStringUTF(msg.c_str());
  jstring jstack = e->NewStringUTF(stack.c_str());
  e->CallStaticVoidMethod(g_jniClass, g_onJsError, jmsg, jstack, (jboolean)fatal);
  e->DeleteLocalRef(jmsg);
  e->DeleteLocalRef(jstack);
}

// Best-effort: rewrite a Hermes stack's `canopy.bundle.js:LINE:COL` frames to `.can` source
// via the JS-side source-map symbolicator the walker installs (globalThis.__canopy_symbolicate,
// fed the in-bundle map in dev). On any failure — no map (release), function not yet installed
// (a pre-program boot throw), or a re-entry exception — returns the raw stack untouched, so
// symbolication never masks the underlying error. Runs on the JS thread (the guards do), so
// touching g_runtime is safe.
std::string symbolicateStack(const std::string& stack) {
  if (!g_runtime || stack.empty()) return stack;
  try {
    jsi::Runtime& rt = *g_runtime;
    jsi::Value fn = rt.global().getProperty(rt, "__canopy_symbolicate");
    if (!fn.isObject() || !fn.getObject(rt).isFunction(rt)) return stack;
    jsi::Value res = fn.getObject(rt).getFunction(rt).call(rt, jsi::String::createFromUtf8(rt, stack));
    if (res.isString()) return res.getString(rt).utf8(rt);
  } catch (...) { /* best-effort — fall through to the raw stack */ }
  return stack;
}

// RNV-2 boot-time ABI gate. Reads the LIVE Hermes ABI off the runtime the host just created
// (HermesRuntime::getBytecodeVersion() — a static on the LINKED engine — and the VM description)
// and compares it to the pin baked from host/vendor.lock.json (canopy::checkHermesAbi). On a
// mismatch the vendored libhermes.so does not match its pinned JSI headers: it would boot here
// and corrupt/SIGABRT on a real device (risk R1). We fail LOUD:
//   • always emit a FATAL-level __android_log line (survives release, no UI needed); and
//   • route the same message to the red-box (reportJsError, fatal=true) — the dev-visible
//     overlay in debug, harmless-but-logged in release.
// Returns true when the ABI matches (boot proceeds), false on mismatch (caller aborts boot
// before evaluating the bundle — a mismatched engine must not run user JS).
bool enforceHermesAbiGate(JNIEnv* e, jsi::Runtime& rt) {
  const int liveBytecode = static_cast<int>(facebook::hermes::HermesRuntime::getBytecodeVersion());
  std::string vmDesc;
  try {
    vmDesc = rt.description();
  } catch (...) {
    vmDesc = "<unavailable>";
  }
  canopy::AbiCheckResult res = canopy::checkHermesAbi(liveBytecode, vmDesc);
  if (res.ok) {
    __android_log_print(ANDROID_LOG_INFO, "CanopyAbiGate", "%s", res.message.c_str());
    return true;
  }
  // Fail-closed. FATAL log first (the only signal in a release build with no dev overlay), then
  // the red-box path so a debug boot stops on a visible screen instead of a later silent crash.
  __android_log_print(ANDROID_LOG_FATAL, "CanopyAbiGate", "%s", res.message.c_str());
  reportJsError(e, res.message, /*stack=*/"Hermes/JSI ABI gate (RNV-2)", /*fatal=*/true);
  return false;
}

// Wrap a JS↔host re-entry; on a JS or native exception, report it (red-box) instead of crash.
template <typename F>
bool guardJsCall(JNIEnv* e, const char* site, bool fatal, F&& fn) {
  try {
    fn();
    return true;
  } catch (facebook::jsi::JSError& err) {
    reportJsError(e, std::string(site) + ": " + err.getMessage(), symbolicateStack(err.getStack()), fatal);
  } catch (const std::exception& ex) {
    reportJsError(e, std::string(site) + " (native): " + ex.what(), "", true);
  } catch (...) {
    reportJsError(e, std::string(site) + " (unknown native exception)", "", true);
  }
  return false;
}
std::mutex g_cbMu;
std::unordered_map<jlong, std::function<void()>> g_callbacks;
jlong g_nextCb = 1;

JNIEnv* env() {
  JNIEnv* e = nullptr;
  g_vm->AttachCurrentThread(&e, nullptr);
  return e;
}

// The C1 worker→JS-thread hop (plan C1 §3.5). Replaces the old inline requestFrame: a
// completion produced on a worker thread is parked in g_callbacks and scheduled onto the
// CanopyJS Looper via Java; runJsCallback() then runs it ON the JS thread, where g_runtime
// lives. Getting this wrong (touching the runtime from the worker thread) is a hard crash.
//
// RND-8: scheduleOnJs(id) targets the SAME Looper the runtime lives on in BOTH modes — the UI
// Looper (single-thread) or the dedicated CanopyJS Looper (off-UI-thread). The Java side owns that
// choice (CanopyHostJni.JS_HANDLER), so this hop needs no change: a completion always re-enters the
// runtime on the thread that owns it.
void postToJs(std::function<void()> fn) {
  jlong id;
  {
    std::lock_guard<std::mutex> g(g_cbMu);
    id = g_nextCb++;
    g_callbacks[id] = std::move(fn);
  }
  JNIEnv* e = env();
  e->CallStaticVoidMethod(g_jniClass, g_scheduleOnJs, id);
}

// RND-8 — the off-UI-thread BatchSink. Runs ON THE JS THREAD inside __fabric_applyBatch (CanopyFabric.
// cpp). It COPIES the frame's flat binary buffer into the UI-thread side-table, then asks Java to post
// applyBatchOnUi(id) onto the UI Looper — so the actual android.view writes happen on the UI thread,
// off the JS/Hermes thread. The copy is mandatory: `data` points into a jsi::ArrayBuffer owned by the
// JS thread that may be GC'd the instant applyBatch returns. Returns true (the frame is now the UI
// thread's responsibility); the runtime's draw moves on without waiting (the whole point — JS work
// decorrelates from view-write latency). Only ever installed when g_jsOffUiThread is true.
bool batchSinkToUi(const uint8_t* data, size_t len) {
  if (g_jniClass == nullptr || g_applyBatchOnUi == nullptr) { return false; }
  jlong id;
  {
    std::lock_guard<std::mutex> g(g_batchMu);
    id = g_nextBatch++;
    g_batchesMarshalled++;
    g_pendingBatches.emplace(id, std::vector<uint8_t>(data, data + len));
  }
  JNIEnv* e = env();
  e->CallStaticVoidMethod(g_jniClass, g_applyBatchOnUi, id);
  return true;
}

// Call a Java CanopyHost method returning int, with (String,String) or (int,...) args.
jclass hostClass(JNIEnv* e) { return e->GetObjectClass(g_javaHost); }

// A CanopyHost C++ shim that forwards every call to the Java object. Only the shapes
// matter here; the Java side (CanopyHost.java) does the real UI work.
class JavaBackedHost : public CanopyHost {
 public:
  Handle createView(const std::string& name, const std::string& props) override {
    JNIEnv* e = env();
    jmethodID m = e->GetMethodID(hostClass(e), "createView", "(Ljava/lang/String;Ljava/lang/String;)I");
    return e->CallIntMethod(g_javaHost, m, e->NewStringUTF(name.c_str()), e->NewStringUTF(props.c_str()));
  }
  // RND-7 batch variant: create at a JS-chosen handle (the batched protocol allocates handles on the
  // JS side). Forwards (handle, name, props) to CanopyHost.createViewWithHandle, which registers the
  // view under THIS handle instead of minting its own. Used only when the walker batches (it does so
  // only because installCanopyFabric advertised __fabric_applyBatch + __fabric_batchHandleBase).
  Handle createView(const std::string& name, const std::string& props, Handle handle) override {
    JNIEnv* e = env();
    jmethodID m = e->GetMethodID(hostClass(e), "createViewWithHandle",
                                 "(ILjava/lang/String;Ljava/lang/String;)I");
    jstring jname = e->NewStringUTF(name.c_str());
    jstring jprops = e->NewStringUTF(props.c_str());
    Handle r = e->CallIntMethod(g_javaHost, m, handle, jname, jprops);
    e->DeleteLocalRef(jname);
    e->DeleteLocalRef(jprops);
    return r;
  }
  void updateProps(Handle h, const std::string& props) override {
    JNIEnv* e = env();
    jmethodID m = e->GetMethodID(hostClass(e), "updateProps", "(ILjava/lang/String;)V");
    e->CallVoidMethod(g_javaHost, m, h, e->NewStringUTF(props.c_str()));
  }
  // __fabric_updatePropScalar(handle, key, value) — the AND-8 single-scalar fast path. Forwards
  // (int, String, String) over JNI exactly like command(), but the Java side does the work with NO
  // `new JSONObject` (CanopyHost.updatePropScalar). This is the JSON-decode cost the fast path
  // eliminates on the Java side; everything object/style/null-shaped still rides updateProps above.
  void updatePropScalar(Handle h, const std::string& key, const std::string& value) override {
    JNIEnv* e = env();
    jmethodID m = e->GetMethodID(hostClass(e), "updatePropScalar",
                                 "(ILjava/lang/String;Ljava/lang/String;)V");
    jstring jkey = e->NewStringUTF(key.c_str());
    jstring jvalue = e->NewStringUTF(value.c_str());
    e->CallVoidMethod(g_javaHost, m, h, jkey, jvalue);
    e->DeleteLocalRef(jkey);
    e->DeleteLocalRef(jvalue);
  }
  void insertChild(Handle p, Handle c, int i) override { call3("insertChild", p, c, i); }
  void removeChild(Handle p, Handle c, int i) override { call3("removeChild", p, c, i); }
  void setRoot(Handle h) override {
    JNIEnv* e = env();
    e->CallVoidMethod(g_javaHost, e->GetMethodID(hostClass(e), "setRoot", "(I)V"), h);
  }
  void setEvents(Handle h, const std::string& names) override {
    JNIEnv* e = env();
    jmethodID m = e->GetMethodID(hostClass(e), "setEvents", "(ILjava/lang/String;)V");
    e->CallVoidMethod(g_javaHost, m, h, e->NewStringUTF(names.c_str()));
  }
  // __fabric_command(handle, name, argsJson) — the AND-3/IOS-8 imperative-op seam. Forwards
  // over JNI exactly like updateProps; the Java side runs the op and emits its result back via
  // CanopyHostJni.emitEvent(handle, "__commandResult", resultJson) (the same emit path press
  // uses). AND-3's Java command() is a trivial echo; focus/measure/scrollTo are AND-4.
  void command(Handle h, const std::string& name, const std::string& argsJson) override {
    JNIEnv* e = env();
    jmethodID m = e->GetMethodID(hostClass(e), "command",
                                 "(ILjava/lang/String;Ljava/lang/String;)V");
    jstring jname = e->NewStringUTF(name.c_str());
    jstring jargs = e->NewStringUTF(argsJson.c_str());
    e->CallVoidMethod(g_javaHost, m, h, jname, jargs);
    e->DeleteLocalRef(jname);
    e->DeleteLocalRef(jargs);
  }
  void requestFrame(std::function<void()> cb) override {
    // Route through the same JS-thread hop as module completions (C1 §3.5). A
    // Choreographer-driven vsync post is the later refinement; the thread-hop correctness
    // (never invoke the runtime off the JS thread) is what matters and is shared here.
    postToJs(std::move(cb));
  }
 private:
  void call3(const char* name, int a, int b, int c) {
    JNIEnv* e = env();
    e->CallVoidMethod(g_javaHost, e->GetMethodID(hostClass(e), name, "(III)V"), a, b, c);
  }
};

std::shared_ptr<CanopyHost> g_host;

}  // namespace

extern "C" {

JNIEXPORT jint JNI_OnLoad(JavaVM* vm, void*) {
  g_vm = vm;
  canopy::jniSetJavaVM(vm);  // share the VM with the portable CanopyJni TU (JniModule + blob bridge)
  return JNI_VERSION_1_6;
}

JNIEXPORT void JNICALL
Java_com_canopyhost_CanopyHostJni_install(JNIEnv* e, jclass jniClass, jobject javaHost) {
  g_javaHost = e->NewGlobalRef(javaHost);
  g_host = std::make_shared<JavaBackedHost>();
  // Cache the CanopyHostJni class + scheduleOnJs(long) so postToJs can schedule onto the
  // JS-thread Looper from native (and from worker threads, via env()).
  g_jniClass = (jclass)e->NewGlobalRef(jniClass);
  g_scheduleOnJs = e->GetStaticMethodID(jniClass, "scheduleOnJs", "(J)V");
  g_onJsError = e->GetStaticMethodID(jniClass, "onJsError", "(Ljava/lang/String;Ljava/lang/String;Z)V");
  // DEV-8: the upcall the reload path uses to surface a 'Model changed' notice to the user (a
  // toast) when a state-preserving reload had to discard the model because the Model type changed
  // shape. Optional — an older CanopyHostJni without the method just leaves g_onReloadNotice null
  // and the reload path skips the toast (the reset still happens; only the toast is absent).
  g_onReloadNotice = e->GetStaticMethodID(jniClass, "onReloadNotice", "(Ljava/lang/String;Ljava/lang/String;)V");
  // RND-8: the upcall the off-UI-thread BatchSink uses to post a frame's view writes onto the UI
  // Looper, and the one-time read of whether off-UI-thread mode is active. Both are optional — an
  // older CanopyHostJni without them leaves the method null + mode false, so boot() installs the
  // Fabric WITHOUT a sink and the host stays single-threaded (JS == UI thread), unchanged.
  g_applyBatchOnUi = e->GetStaticMethodID(jniClass, "applyBatchOnUi", "(J)V");
  jmethodID offUi = e->GetStaticMethodID(jniClass, "jsOffUiThread", "()Z");
  g_jsOffUiThread = (offUi != nullptr) && (g_applyBatchOnUi != nullptr)
                    && e->CallStaticBooleanMethod(jniClass, offUi);
  __android_log_print(ANDROID_LOG_INFO, "CanopyThread",
                      "JS thread mode: %s", g_jsOffUiThread ? "DEDICATED (off UI thread, RND-8)"
                                                            : "UI thread (single-thread)");
}

// Minimal `console` polyfill. Bare Hermes ships no `console` global (React Native installs one
// from JS); the compiled Canopy bundle's effect-manager runtime references it, so install
// log/info/warn/error/debug/trace → __android_log under the "CanopyJS" tag.
static void installConsole(jsi::Runtime& rt) {
  auto logger = [](int prio) {
    return [prio](jsi::Runtime& rt, const jsi::Value&, const jsi::Value* args,
                  size_t count) -> jsi::Value {
      std::string line;
      for (size_t i = 0; i < count; i++) {
        if (i) line += " ";
        try {
          line += args[i].toString(rt).utf8(rt);
        } catch (...) {
          line += "<?>";
        }
      }
      __android_log_print(prio, "CanopyJS", "%s", line.c_str());
      return jsi::Value::undefined();
    };
  };
  jsi::Object console(rt);
  struct Method { const char* name; int prio; };
  const Method methods[] = {
      {"log", ANDROID_LOG_INFO},    {"info", ANDROID_LOG_INFO},
      {"warn", ANDROID_LOG_WARN},   {"error", ANDROID_LOG_ERROR},
      {"debug", ANDROID_LOG_DEBUG}, {"trace", ANDROID_LOG_VERBOSE},
  };
  for (const Method& m : methods) {
    console.setProperty(
        rt, m.name,
        jsi::Function::createFromHostFunction(
            rt, jsi::PropNameID::forAscii(rt, m.name), 1, logger(m.prio)));
  }
  rt.global().setProperty(rt, "console", console);
}

// RNV-7 load-time gate: before handing a bundle buffer to Hermes, check that — IF it is a real
// .hbc — its stamped bytecode-format version equals the vendored engine pin (the load-time half of
// the RNV-2 contract; checkBundleBytecode is a no-op for plain JS source). A mismatch means the
// .hbc was compiled by a hermesc whose HBC format differs from the linked engine: the engine would
// reject it. We fail LOUD (fatal log + red-box) and bail BEFORE evaluation, exactly like the engine
// ABI gate. Returns true when the buffer is safe to evaluate.
bool enforceBundleBytecodeGate(JNIEnv* e, const std::string& bundle) {
  canopy::AbiCheckResult res = canopy::checkBundleBytecode(
      reinterpret_cast<const uint8_t*>(bundle.data()), bundle.size());
  if (res.ok) {
    __android_log_print(ANDROID_LOG_INFO, "CanopyAbiGate", "%s", res.message.c_str());
    return true;
  }
  __android_log_print(ANDROID_LOG_FATAL, "CanopyAbiGate", "%s", res.message.c_str());
  reportJsError(e, res.message, /*stack=*/"Hermes .hbc load gate (RNV-7)", /*fatal=*/true);
  return false;
}

JNIEXPORT void JNICALL
Java_com_canopyhost_CanopyHostJni_nativeBoot(JNIEnv* e, jclass, jbyteArray bundle, jstring flagsJson) {
  // THREADING (C1 §3.5).
  //   • DEFAULT (single-thread): the JS thread IS the main/UI thread — the same posture as the iOS
  //     template — because every __fabric_* mount call touches android.view, which must run on the UI
  //     thread. g_runtime is created + owned on the thread that calls boot(), and postToJs's Looper is
  //     the main Looper. Heavy module work runs on its OWN worker thread (e.g. EchoModule's std::thread)
  //     and hops its completion back via postToJs → JS Looper → __canopy_resolve.
  //   • RND-8 (off-UI-thread, g_jsOffUiThread): the JS thread is a DEDICATED "CanopyJS" thread.
  //     boot() runs ON IT (Java posts it onto the CanopyJS Looper), so g_runtime is created + owned
  //     there — never touched off it. The walker's per-frame view writes do NOT mutate android.view
  //     inline; instead installCanopyFabric is given the batchSinkToUi BatchSink, which ships each
  //     frame's ONE flat binary batch (RND-7) to the UI thread for replay. postToJs likewise targets
  //     the CanopyJS Looper (the runtime's home), so module/event completions still re-enter the
  //     runtime on its owning thread. This is the "move JS off the UI thread + marshal mounts to it"
  //     refactor the master plan (RND-8) gates behind a flag.
  //
  // RNV-7: the bundle arrives as RAW BYTES (jbyteArray), not a UTF-8 jstring, so a real Hermes
  // .hbc (binary bytecode) survives the JNI boundary intact. Hermes' evaluateJavaScript detects
  // the HBC magic and runs bytecode directly (no parse); plain JS source still evaluates as before.
  jsize bundleLen = e->GetArrayLength(bundle);
  std::string srcStr;
  srcStr.resize(static_cast<size_t>(bundleLen));
  if (bundleLen > 0) {
    e->GetByteArrayRegion(bundle, 0, bundleLen, reinterpret_cast<jbyte*>(&srcStr[0]));
  }
  const char* flags = e->GetStringUTFChars(flagsJson, nullptr);

  // RNV-4: create the Hermes-backed jsi::Runtime through the ONE factory (CanopyHermes.cpp). This
  // boot site no longer names a Hermes engine symbol — a Hermes engine swap is a one-file change
  // behind canopy::makeRuntime(). The backend (C++ makeHermesRuntime today, or the stable C-vtable
  // makeHermesABIRuntimeWrapper under -DCANOPY_HERMES_CABI once RNV-6 vendors a standalone Hermes
  // that exports get_hermes_abi_vtable) is selected at compile time inside that file.
  __android_log_print(ANDROID_LOG_INFO, "CanopyHermes", "creating runtime via %s",
                      canopy::makeRuntimeBackendName());
  g_runtime = canopy::makeRuntime();

  // RNV-2: gate the linked Hermes/JSI ABI against the vendored pin BEFORE installing anything or
  // evaluating the bundle. A mismatched libhermes must never run user JS — it boots fine here and
  // corrupts on a real device. Fail-closed: log fatal + red-box, then bail out of boot.
  if (!enforceHermesAbiGate(e, *g_runtime)) {
    g_runtime.reset();
    e->ReleaseStringUTFChars(flagsJson, flags);
    return;
  }

  // RNV-7: gate the BUNDLE's bytecode version (if it is a real .hbc) against the same engine pin,
  // also BEFORE evaluation — a wrong-toolchain .hbc would be rejected by Hermes mid-eval otherwise.
  if (!enforceBundleBytecodeGate(e, srcStr)) {
    g_runtime.reset();
    e->ReleaseStringUTFChars(flagsJson, flags);
    return;
  }

  // RND-8: in off-UI-thread mode, pass the batchSinkToUi sink so __fabric_applyBatch marshals each
  // frame's binary batch to the UI thread instead of mutating android.view on this (CanopyJS) thread.
  // In the default single-thread mode the sink is null, so __fabric_applyBatch replays inline exactly
  // as before — this boot path is BYTE-FOR-BYTE unchanged when the flag is off.
  installCanopyFabric(*g_runtime, g_host, g_jsOffUiThread ? canopy::BatchSink(batchSinkToUi) : nullptr);

  // C1: install the native-module ABI and register capabilities. The registry holds the
  // runtime + the postToJs hop; async results re-enter Hermes only through that hop.
  // Alias g_blobs to the ONE process-wide registry the blob bridge + CanopyBitmap renderer +
  // ORT all share (a handle minted in ImageModule.decode is the same one ORT + the renderer see).
  g_blobs = std::shared_ptr<BlobRegistry>(&canopy::globalBlobRegistry(), [](BlobRegistry*){});
  g_registry = std::make_shared<ModuleRegistry>();
  g_registry->setRuntime(g_runtime.get());
  g_registry->setPostToJs(postToJs);
  installCanopyModules(*g_runtime, g_registry);
  g_registry->registerModule(std::make_shared<EchoModule>());  // C1 first-light capability

  // ── Autolinked capabilities (AUTO-E-DELETE / plan §5 Phase E) ──────────────────────────────
  // The per-capability registration block that used to live HERE — one JniModule("<Name>") line
  // per capability (Image/Album/ShareImage/StorageSecure/Notify/Http/Platform/Vibration/Battery/
  // DeviceInfo/NetInfo/Haptics/Brightness), plus globalBillingModule() and the two
  // globalStreamingModule(...) instances for canopy/navigation's Lifecycle + AppShell — is GONE.
  // Every one of those capabilities is now PACKAGE-RESIDENT: it ships its own native/android impl
  // and declares itself in its package's native.json, and `canopy-native build` emits the
  // registration into generated/CanopyGeneratedRegistrant.h from the app's dependency graph (the
  // native analogue of the web compiler concatenating each package's external/*.js). Adding a
  // capability is now "add a dependency" — ZERO edits to this file, ever again.
  //
  // canopyRegisterGeneratedModules() (the generated registrant) is therefore the SOLE source of
  // capability registration. It is #if __has_include-guarded at the top of this file so an
  // un-autolinked checkout (no `canopy-native build` run yet) still compiles + boots — it simply
  // registers no autolinked capabilities until a build generates the registrant.
#ifdef CANOPY_HAS_GENERATED_REGISTRANT
  canopy::canopyRegisterGeneratedModules(*g_registry);
#endif

  // Two capabilities stay HOST-RESIDENT by design — they are NOT autolinked, because each needs
  // host-specific wiring the generated registrant cannot synthesize:
  //
  //   • Photos — its picker rides MainActivity's registerForActivityResult launcher, and
  //     MainActivity statically calls PhotosModule.onPickResult (MainActivity.java:69-75). That
  //     Activity-result coupling is not pure-JNI, so Photos is not a self-contained package and is
  //     registered here by name (canopy/photos ships no native.json — see Extract.hs pureJniSpecs).
  g_registry->registerModule(std::make_shared<canopy::JniModule>("Photos"));
  //   • RestoreEngine (canopy/inference) — a C++ NativeModule whose ORT model BYTES are handed in
  //     AFTER boot via Java_..._nativeSetRestoreEngineModel. The host holds the instance pointer
  //     (g_restoreEngine) to fill it later, so its construction stays here (the generated registrant
  //     emits only a comment for this kind=cpp/no-factory module).
  g_restoreEngine = std::make_shared<canopy::RestoreEngineModule>();
  g_registry->registerModule(g_restoreEngine);

  // Bare Hermes has no `console`; the bundle's runtime references it. Install before eval.
  installConsole(*g_runtime);

  // Guarded boot: a bundle syntax error, a missing main module, or a throw inside the first
  // synchronous view(model) becomes a red-box (fatal: there is no running program), not SIGABRT.
  // srcStr was filled from the jbyteArray above — for a real .hbc it holds binary bytecode, which
  // Hermes' evaluateJavaScript runs directly (isHermesBytecode); for JS source it parses as before.
  std::string flagsStr(flags);
  g_bootFlags = flagsStr;  // cached for a later in-process reload (re-boot with the same flags)
  // Name the eval source after the actual bundle kind so a Hermes stack/log is unambiguous.
  const char* sourceUrl =
      canopy::looksLikeHermesBytecode(reinterpret_cast<const uint8_t*>(srcStr.data()), srcStr.size())
          ? "canopy.bundle.hbc"
          : "canopy.bundle.js";
  guardJsCall(e, "boot", /*fatal=*/true, [&]() {
    g_runtime->evaluateJavaScript(
        std::make_shared<jsi::StringBuffer>(srcStr), sourceUrl);
    // Create the host root ONCE and cache it; reload() re-boots onto this same handle so the
    // surface's root view (and the rest of the host view tree it anchors) is preserved.
    g_rootTag = g_host->createView("RCTRootView", "{\"style\":{\"flex\":\"1\"}}");
    canopyBoot(*g_runtime, g_rootTag, flagsStr);
  });

  // RND-8 sanity gate: off-UI-thread mode REQUIRES a batching (RND-7) bundle. The boot's initial
  // render is ONE batch — so if off-UI-thread mode is on but the boot frame marshalled ZERO batches
  // through the sink, the bundle is NOT using the batch seam (an older per-mutation bundle). On such a
  // bundle the walker would call the host's android.view methods DIRECTLY on the CanopyJS thread,
  // which throws CalledFromWrongThreadException the moment a view is window-attached (a confusing
  // crash far from the cause). We surface the real cause LOUD here instead — a fatal log + red-box —
  // exactly like the ABI gates. (We do not auto-disable: the flag is a deliberate, debug-only opt-in,
  // so the correct fix is to ship a batching bundle, not to silently fall back.)
  if (g_jsOffUiThread && g_batchesMarshalled == 0) {
    const char* msg = "RND-8: off-UI-thread mode (debug.canopy.jsthread) is ON but the bundle does "
                      "not batch (RND-7). A per-mutation bundle cannot run off the UI thread — rebuild "
                      "with a batching native.js, or disable the flag.";
    __android_log_print(ANDROID_LOG_FATAL, "CanopyThread", "%s", msg);
    reportJsError(e, msg, "RND-8 off-UI-thread requires a batched bundle", /*fatal=*/true);
  }

  e->ReleaseStringUTFChars(flagsJson, flags);
}

// DEV-4 — call a 0-arg JS reload-seam function on the live runtime, returning whether it ran and
// reported true. The seam (native.js: __canopy_captureState / __canopy_teardown) is published only
// by a BOOTED debug program; if it is absent (a release bundle, or a never-booted runtime) this is a
// no-op returning false, so reload() degrades to a clean re-eval. Runs on the JS thread (the caller
// guarantees it), so touching g_runtime is safe.
bool callReloadSeam(jsi::Runtime& rt, const char* name) {
  jsi::Value fn = rt.global().getProperty(rt, name);
  if (!fn.isObject() || !fn.getObject(rt).isFunction(rt)) return false;
  jsi::Value res = fn.getObject(rt).getFunction(rt).call(rt);
  return res.isBool() && res.getBool();
}

// DEV-8 — drain the developer-facing notice native.js posts on globalThis.__canopy_reloadNotice when
// a state-preserving reload had to DISCARD the captured model because the new bundle's Model type-hash
// differs from the old one (an incompatible Model shape across the edit). The notice is { kind, message
// }; we forward it to Java (CanopyHostJni.onReloadNotice → a toast) and then CLEAR the global so a
// later compatible reload — which posts nothing — is not mistaken for a repeat of this one. A reload
// that preserved state leaves no notice, so this is a no-op then. Runs on the JS thread (the reload
// caller guarantees it), so reading the global is safe.
void drainReloadNotice(JNIEnv* e, jsi::Runtime& rt) {
  jsi::Value v = rt.global().getProperty(rt, "__canopy_reloadNotice");
  if (!v.isObject()) return;
  jsi::Object o = v.getObject(rt);
  auto readStr = [&](const char* key) -> std::string {
    jsi::Value f = o.getProperty(rt, key);
    return f.isString() ? f.getString(rt).utf8(rt) : std::string();
  };
  std::string kind = readStr("kind");
  std::string message = readStr("message");
  // Clear the global first so the notice is consumed exactly once, regardless of whether the upcall
  // below is available (an older CanopyHostJni).
  rt.global().setProperty(rt, "__canopy_reloadNotice", jsi::Value::undefined());
  if (e && g_jniClass && g_onReloadNotice) {
    jstring jkind = e->NewStringUTF(kind.c_str());
    jstring jmsg = e->NewStringUTF(message.c_str());
    e->CallStaticVoidMethod(g_jniClass, g_onReloadNotice, jkind, jmsg);
    e->DeleteLocalRef(jkind);
    e->DeleteLocalRef(jmsg);
  }
}

// Run a parked postToJs callback. Java's scheduleOnJs posted this onto the CanopyJS Looper,
// so we are now ON the JS thread — safe to touch g_runtime (canopyResolveCall runs here).
JNIEXPORT void JNICALL
Java_com_canopyhost_CanopyHostJni_runJsCallback(JNIEnv* e, jclass, jlong id) {
  std::function<void()> fn;
  {
    std::lock_guard<std::mutex> g(g_cbMu);
    auto it = g_callbacks.find(id);
    if (it == g_callbacks.end()) { return; }
    fn = std::move(it->second);
    g_callbacks.erase(it);
  }
  // The highest-frequency re-entry: every Cmd/Sub completion + event re-enters update/view
  // here. A throw in the app's update/view (or a decoder) becomes a red-box, not a SIGABRT.
  if (fn) { guardJsCall(e, "callback", /*fatal=*/false, [&]() { fn(); }); }
}

// RND-8 — replay a frame's marshalled binary batch ON THE UI THREAD. Java's applyBatchOnUi posted
// this onto the UI Looper (off-UI-thread mode only); we are now on the UI thread, where android.view
// writes are legal, so we pull the frame's bytes from the side-table and replay them against the host
// via canopyApplyBinaryBatch — the SAME decoder the inline path uses, just reached from the UI thread.
//
// IMPORTANT: this does NOT touch g_runtime. The shared decoder marshals the flat buffer straight to
// CanopyHost methods (createView/updateProps/insertChild/…) — no jsi::Value, no JS call — so it is
// safe on the UI thread even though g_runtime lives on the CanopyJS thread. Guarded so a malformed
// buffer (truncation throws a jsi::JSError) or a host exception becomes a red-box, never a SIGABRT.
// `runtime` is passed to the decoder only to carry the JSError type on a truncated buffer; no JS runs.
JNIEXPORT void JNICALL
Java_com_canopyhost_CanopyHostJni_runUiBatch(JNIEnv* e, jclass, jlong id) {
  std::vector<uint8_t> bytes;
  {
    std::lock_guard<std::mutex> g(g_batchMu);
    auto it = g_pendingBatches.find(id);
    if (it == g_pendingBatches.end()) { return; }  // already drained / unknown — no-op
    bytes = std::move(it->second);
    g_pendingBatches.erase(it);
  }
  if (!g_runtime || bytes.empty()) { return; }
  guardJsCall(e, "uiBatch", /*fatal=*/false, [&]() {
    canopyApplyBinaryBatch(*g_runtime, *g_host, bytes.data(), bytes.size());
  });
}

JNIEXPORT void JNICALL
Java_com_canopyhost_CanopyHostJni_nativeEmitEvent(JNIEnv* e, jclass, jint handle, jstring name, jstring payload) {
  const char* n = e->GetStringUTFChars(name, nullptr);
  const char* p = e->GetStringUTFChars(payload, nullptr);
  std::string nStr(n), pStr(p);
  // A throw in the press/gesture handler (update) becomes a red-box, not a SIGABRT.
  if (g_runtime) {
    guardJsCall(e, "event", /*fatal=*/false, [&]() {
      canopyEmitEvent(*g_runtime, handle, nStr, pStr);
    });
  }
  e->ReleaseStringUTFChars(name, n);
  e->ReleaseStringUTFChars(payload, p);
}

// REL-2 SIG — install the native hard-crash floor (SIGSEGV/SIGABRT/SIGBUS/SIGILL/SIGFPE). Called by
// CanopyCrashFloor.install ONLY when the CANOPY_SIGNAL_FLOOR opt-in is set (off by default — a buggy
// async-signal handler is a net reliability regression; see CanopySignalFloor.h). Records the same
// buildId/sessionId crash breadcrumb the REL-4 metric reads, then chains the prior disposition.
JNIEXPORT void JNICALL
Java_com_canopyhost_CanopyHostJni_installSignalFloor(JNIEnv* e, jclass, jstring dir, jstring buildId,
                                                     jstring sessionId, jstring source) {
  const char* d = e->GetStringUTFChars(dir, nullptr);
  const char* b = e->GetStringUTFChars(buildId, nullptr);
  const char* s = e->GetStringUTFChars(sessionId, nullptr);
  const char* src = e->GetStringUTFChars(source, nullptr);
  canopy::installSignalFloor(d, b, s, "android", src);
  e->ReleaseStringUTFChars(dir, d);
  e->ReleaseStringUTFChars(buildId, b);
  e->ReleaseStringUTFChars(sessionId, s);
  e->ReleaseStringUTFChars(source, src);
}

// DEV-4 — in-process, state-preserving reload (the dev-loop's edit→see cycle without a fresh
// process). Re-evaluates the new bundle on the SAME Hermes runtime and re-boots onto the SAME cached
// root, preserving the host view tree (only the program's mounted subtree under the root is rebuilt)
// and the user's TEA model. This is the host half of the DEV-2 reload seam (native.js owns the JS
// half: __canopy_captureState / __canopy_teardown / __canopy_remount). Must run on the JS/UI thread
// (Java posts it onto the JS Looper before calling), where g_runtime lives.
//
// Sequence (mirrors harness/run-reload-seam.js, which drives this exact loop device-free):
//   1. captureState() — read the live TEA model so it survives the new-bundle eval (an opaque
//      { model } carrier; null in a release bundle / a never-booted runtime → a cold reload).
//   2. teardown()     — stop the running Subs (so the reload does not double-subscribe) and release
//      THIS program's mounted subtree under the cached root, leaving a clean root view.
//   3. clear globalThis.Canopy + scope.Canopy (+ the Elm alias) — the host's reset step: the
//      compiler's _Platform_export rejects a duplicate Canopy.Main on the same runtime, so a
//      re-eval must clear it first (DEV-4's plan note: "verify IIFE re-eval is idempotent; fall
//      back to clean in-process reboot if not").
//   4. evaluateJavaScript(newBundle) — re-eval on the SAME runtime (same modules, same console/ABI).
//   5. __canopy_boot(cachedRootTag, flags) — re-boot onto the SAME root handle (host view preserved).
//   6. remount(captured) — restore the captured model into the freshly-booted program (the user
//      lands back where they were — the whole point vs. a cold restart).
//
// Guarded end-to-end: a syntax error / throw in the NEW bundle becomes a red-box (fatal: the old
// program is already torn down, so there is no running program to fall back to), not a SIGABRT.
//
// Bound to CanopyHost.nativeReload (a static native) — the reload ENTRY lives on the mount object
// (CanopyHost) that owns the host view tree this preserves, while boot/install/emit stay on
// CanopyHostJni. libcanopyhost.so is already loaded (CanopyHostJni's static block) before any
// CanopyHost exists, so resolving this symbol off CanopyHost is safe.
JNIEXPORT void JNICALL
Java_com_canopyhost_CanopyHost_nativeReload(JNIEnv* e, jclass, jstring newBundleJs) {
  if (!g_runtime || g_rootTag < 0) {
    // Never booted (or a boot that aborted at the ABI gate): nothing to reload onto. A red-box
    // explains it rather than silently doing nothing.
    reportJsError(e, "reload: no booted runtime to reload onto", "DEV-4 in-process reload", /*fatal=*/false);
    return;
  }
  const char* src = e->GetStringUTFChars(newBundleJs, nullptr);
  std::string srcStr(src ? src : "");
  e->ReleaseStringUTFChars(newBundleJs, src);

  guardJsCall(e, "reload", /*fatal=*/true, [&]() {
    jsi::Runtime& rt = *g_runtime;

    // (1) capture the live model (survives the new eval). The carrier is an opaque JS object the
    // walker minted; we hold it on the JS stack across the eval and thread it back into remount.
    jsi::Value captured = jsi::Value::null();
    {
      jsi::Value cap = rt.global().getProperty(rt, "__canopy_captureState");
      if (cap.isObject() && cap.getObject(rt).isFunction(rt)) {
        captured = cap.getObject(rt).getFunction(rt).call(rt);
      }
    }

    // (2) tear the live program down (stop Subs + release the mounted subtree under the root).
    callReloadSeam(rt, "__canopy_teardown");

    // (3) the host reset: clear Canopy (the canonical export target _Platform_export checks) plus the
    // Elm back-compat alias, so the re-eval's _Platform_export accepts the new Canopy.Main. We clear
    // on the global and on `scope` (the compiler exports under either depending on the IIFE shape);
    // a missing property is harmless (setting it to undefined is idempotent).
    rt.global().setProperty(rt, "Canopy", jsi::Value::undefined());
    rt.global().setProperty(rt, "Elm", jsi::Value::undefined());
    {
      jsi::Value scope = rt.global().getProperty(rt, "scope");
      if (scope.isObject()) {
        scope.getObject(rt).setProperty(rt, "Canopy", jsi::Value::undefined());
        scope.getObject(rt).setProperty(rt, "Elm", jsi::Value::undefined());
      }
    }

    // (4) re-evaluate the NEW bundle on the SAME runtime. The DEV-4 reload path carries JS SOURCE
    // (the dev loop pushes JS for a fast edit→see cycle — no hermesc round-trip); the .hbc bytecode
    // path is the baked-asset/production boot in Java_..._boot. evaluateJavaScript would run either.
    rt.evaluateJavaScript(std::make_shared<jsi::StringBuffer>(srcStr), "canopy.bundle.js (reload)");

    // (5) re-boot onto the SAME cached root handle (the host root view + surface are untouched) with
    // the SAME flags the program first booted with.
    canopyBoot(rt, g_rootTag, g_bootFlags);

    // (6) restore the captured model into the freshly-booted program. A null carrier (release bundle
    // / no live state) makes remount a no-op — the reloaded program just keeps its init model. DEV-8:
    // remount restores the model ONLY when the new bundle's Model type-hash matches the captured one;
    // on a mismatch it keeps the fresh init model and posts a 'Model changed' notice instead.
    jsi::Value rem = rt.global().getProperty(rt, "__canopy_remount");
    if (rem.isObject() && rem.getObject(rt).isFunction(rt)) {
      rem.getObject(rt).getFunction(rt).call(rt, captured);
    }

    // (7) DEV-8: surface any 'Model changed' notice remount posted (an incompatible reload discarded
    // the model). A compatible reload posts nothing, so this is a no-op then.
    drainReloadNotice(e, rt);
  });
}

// Hand the ORT model bytes (read from assets by MainActivity after boot) to the engine.
// (resolveModule + the nativeBlob* exports live in CanopyJni.cpp — do not redefine them here.)
JNIEXPORT void JNICALL
Java_com_canopyhost_CanopyHostJni_nativeSetRestoreEngineModel(JNIEnv* e, jclass, jbyteArray bytes) {
  if (!g_restoreEngine || bytes == nullptr) return;
  jsize n = e->GetArrayLength(bytes);
  jbyte* p = e->GetByteArrayElements(bytes, nullptr);
  g_restoreEngine->setModelBytes(reinterpret_cast<const uint8_t*>(p), (size_t)n);
  e->ReleaseByteArrayElements(bytes, p, JNI_ABORT);
}

}  // extern "C"
